/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

/**
 * A live child process created with `start_process`.
 * 
 * `stdout` is consumed incrementally. Stderr inherits the parent process so
 * diagnostics remain visible without risking a blocked, unread stderr pipe.
 */
export class Process$stream {
  stdout!: ProcessLineStream$stream | null;
  _handle!: _BamlHandle;
  constructor(init: {
    stdout: ProcessLineStream$stream | null;
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The terminal status of a process created with `start_process`.
 */
export class ProcessExit$stream {
  exit_code!: number | null;
  signal!: string | null;
  constructor(init: {
    exit_code: number | null;
    signal: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A live line-oriented child-process output stream.
 * 
 * Iteration waits for one complete UTF-8 line without blocking other BAML
 * green threads. The final unterminated line is yielded at EOF.
 */
export class ProcessLineStream$stream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Options for `exec`, `start_process`, and `shell`.
 *
 * Attributes:
 *   cwd: Working directory for the child process.
 *   env: Environment variables to set for the child process.
 *   timeout_ms: Maximum time in milliseconds to wait for the process to complete.
 *   stdin: Data to write to the child process's stdin.
 *   keep_stdin_open: Keep a writable stdin pipe on a process returned by `start_process`.
 *     
 *     When this is `true`, use `Process.write_stdin` to send data incrementally
 *     and `Process.close_stdin` to deliver EOF. This option has no effect on
 *     `exec` or `shell`.
 */
export class ProcessOptions$stream {
  cwd!: string | null;
  env!: { [key: string]: string } | null;
  timeout_ms!: number | null;
  stdin!: string | null;
  keep_stdin_open!: boolean | null;
  constructor(init: {
    cwd: string | null;
    env: { [key: string]: string } | null;
    timeout_ms: number | null;
    stdin: string | null;
    keep_stdin_open: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The result of running an external process with `exec` or `shell`.
 */
export class ShellOutput$stream {
  stdout!: Uint8Array;
  stderr!: Uint8Array;
  exit_code!: number | null;
  constructor(init: {
    stdout: Uint8Array;
    stderr: Uint8Array;
    exit_code: number | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Options for `exec`, `start_process`, and `shell`.
 *
 * Attributes:
 *   cwd: Working directory for the child process.
 *   env: Environment variables to set for the child process.
 *   timeout_ms: Maximum time in milliseconds to wait for the process to complete.
 *   stdin: Data to write to the child process's stdin.
 *   keep_stdin_open: Keep a writable stdin pipe on a process returned by `start_process`.
 *     
 *     When this is `true`, use `Process.write_stdin` to send data incrementally
 *     and `Process.close_stdin` to deliver EOF. This option has no effect on
 *     `exec` or `shell`.
 */
export class ProcessOptions {
  cwd!: string | null;
  env!: { [key: string]: string } | null;
  timeout_ms!: number | null;
  stdin!: string | null;
  keep_stdin_open!: boolean | null;
  constructor(init: {
    cwd: string | null;
    env: { [key: string]: string } | null;
    timeout_ms: number | null;
    stdin: string | null;
    keep_stdin_open: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The result of running an external process with `exec` or `shell`.
 */
export class ShellOutput {
  stdout!: Uint8Array;
  stderr!: Uint8Array;
  exit_code!: number;
  constructor(init: {
    stdout: Uint8Array;
    stderr: Uint8Array;
    exit_code: number;
  }) {
    Object.assign(this, init);
  }
/**
 * Returns `true` if the process exited with code `0`.
 */
  ok = defineInstanceFunction("baml.sys.ShellOutput.ok", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;
/**
 * Returns `true` if the process exited with code `0`.
 */
  ok_async = defineInstanceFunction("baml.sys.ShellOutput.ok", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;
}

/**
 * The terminal status of a process created with `start_process`.
 */
export class ProcessExit {
  exit_code!: number;
  signal!: string | null;
  constructor(init: {
    exit_code: number;
    signal: string | null;
  }) {
    Object.assign(this, init);
  }
/**
 * Returns `true` if the process exited normally with code `0`.
 */
  ok = defineInstanceFunction("baml.sys.ProcessExit.ok", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;
/**
 * Returns `true` if the process exited normally with code `0`.
 */
  ok_async = defineInstanceFunction("baml.sys.ProcessExit.ok", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;
}

/**
 * A live line-oriented child-process output stream.
 * 
 * Iteration waits for one complete UTF-8 line without blocking other BAML
 * green threads. The final unterminated line is yielded at EOF.
 */
export class ProcessLineStream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Wait for and return the next line, or `null` at EOF.
 * @throws Io
 * @throws Timeout
 */
  _next = defineInstanceFunction("baml.sys.ProcessLineStream._next", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;
/**
 * Wait for and return the next line, or `null` at EOF.
 * @throws Io
 * @throws Timeout
 */
  _next_async = defineInstanceFunction("baml.sys.ProcessLineStream._next", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;
/**
 * Stop reading this stream. Later reads return EOF.
 */
  close = defineInstanceFunction("baml.sys.ProcessLineStream.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Stop reading this stream. Later reads return EOF.
 */
  close_async = defineInstanceFunction("baml.sys.ProcessLineStream.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}

/**
 * A live child process created with `start_process`.
 * 
 * `stdout` is consumed incrementally. Stderr inherits the parent process so
 * diagnostics remain visible without risking a blocked, unread stderr pipe.
 */
export class Process {
  stdout!: ProcessLineStream;
  _handle!: _BamlHandle;
  constructor(init: {
    stdout: ProcessLineStream;
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Write data to the child process's open stdin pipe.
 * @throws Io
 */
  write_stdin = defineInstanceFunction("baml.sys.Process.write_stdin", "sync", ["self", "data"]).bind(this) as (data: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Write data to the child process's open stdin pipe.
 * @throws Io
 */
  write_stdin_async = defineInstanceFunction("baml.sys.Process.write_stdin", "async", ["self", "data"]).bind(this) as (data: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * Close the child process's stdin pipe, delivering EOF.
 * @throws Io
 */
  close_stdin = defineInstanceFunction("baml.sys.Process.close_stdin", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Close the child process's stdin pipe, delivering EOF.
 * @throws Io
 */
  close_stdin_async = defineInstanceFunction("baml.sys.Process.close_stdin", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * Wait for the child to exit.
 * @throws Io
 * @throws Timeout
 */
  wait = defineInstanceFunction("baml.sys.Process.wait", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ProcessExit;
/**
 * Wait for the child to exit.
 * @throws Io
 * @throws Timeout
 */
  wait_async = defineInstanceFunction("baml.sys.Process.wait", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ProcessExit>;
/**
 * Request that the child terminate.
 * @throws Io
 */
  kill = defineInstanceFunction("baml.sys.Process.kill", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Request that the child terminate.
 * @throws Io
 */
  kill_async = defineInstanceFunction("baml.sys.Process.kill", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * Terminate an un-waited child and close its stdout stream.
 * 
 * Safe to use with `defer { process.close() }`.
 */
  close = defineInstanceFunction("baml.sys.Process.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Terminate an un-waited child and close its stdout stream.
 * 
 * Safe to use with `defer { process.close() }`.
 */
  close_async = defineInstanceFunction("baml.sys.Process.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}

/**
 * Runs `program` with the given `args` and returns its output. Throws on I/O failure or timeout.
 * @throws Io
 * @throws Timeout
 */
export const exec = defineFunction("baml.sys.exec", "sync", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ShellOutput;

/**
 * Runs `program` with the given `args` and returns its output. Throws on I/O failure or timeout.
 * @throws Io
 * @throws Timeout
 */
export const exec_async = defineFunction("baml.sys.exec", "async", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ShellOutput>;

/**
 * Starts `program` and returns immediately with a live stdout line stream.
 * 
 * Unlike `exec`, output is not buffered until process exit. Reading
 * `process.stdout` suspends only the current BAML green thread.
 * @throws Io
 */
export const start_process = defineFunction("baml.sys.start_process", "sync", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Process;

/**
 * Starts `program` and returns immediately with a live stdout line stream.
 * 
 * Unlike `exec`, output is not buffered until process exit. Reading
 * `process.stdout` suspends only the current BAML green thread.
 * @throws Io
 */
export const start_process_async = defineFunction("baml.sys.start_process", "async", ["program", "args", "options"]) as (program: string, args: string[] | null, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Process>;

/**
 * Runs a shell `command` string (passed to `/bin/sh -c`) and returns its output.
 * @throws Io
 * @throws Timeout
 */
export const shell = defineFunction("baml.sys.shell", "sync", ["command", "options"]) as (command: string, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ShellOutput;

/**
 * Runs a shell `command` string (passed to `/bin/sh -c`) and returns its output.
 * @throws Io
 * @throws Timeout
 */
export const shell_async = defineFunction("baml.sys.shell", "async", ["command", "options"]) as (command: string, options: ProcessOptions | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ShellOutput>;

/**
 * Suspends the current thread for `delay`.
 * @throws Io
 */
export const sleep = defineFunction("baml.sys.sleep", "sync", ["delay"]) as (delay: baml.time.Duration, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Suspends the current thread for `delay`.
 * @throws Io
 */
export const sleep_async = defineFunction("baml.sys.sleep", "async", ["delay"]) as (delay: baml.time.Duration, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

/**
 * Forces a full garbage collection and runs queued `cleanup()` finalizers before returning.
 * Intended for deterministic tests and runtime diagnostics; production code should normally
 * let the runtime schedule collections automatically.
 */
export const collect_garbage = defineFunction("baml.sys.collect_garbage", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Forces a full garbage collection and runs queued `cleanup()` finalizers before returning.
 * Intended for deterministic tests and runtime diagnostics; production code should normally
 * let the runtime schedule collections automatically.
 */
export const collect_garbage_async = defineFunction("baml.sys.collect_garbage", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

export const panic = defineFunction("baml.sys.panic", "sync", ["message"]) as (message: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => never;

export const panic_async = defineFunction("baml.sys.panic", "async", ["message"]) as (message: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<never>;

export const exit = defineFunction("baml.sys.exit", "sync", ["code"]) as (code: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => never;

export const exit_async = defineFunction("baml.sys.exit", "async", ["code"]) as (code: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<never>;

/**
 * Returns the command-line arguments passed to the BAML program, as an array of strings.
 */
export const argv = defineFunction("baml.sys.argv", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string[];

/**
 * Returns the command-line arguments passed to the BAML program, as an array of strings.
 */
export const argv_async = defineFunction("baml.sys.argv", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string[]>;

/**
 * Returns the process ID of the current process.
 * 
 * ## Panics
 * If the environment does not support process IDs (e.g. in a browser), with
 * `baml.panics.HostUnavailable`.
 */
export const pid = defineFunction("baml.sys.pid", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;

/**
 * Returns the process ID of the current process.
 * 
 * ## Panics
 * If the environment does not support process IDs (e.g. in a browser), with
 * `baml.panics.HostUnavailable`.
 */
export const pid_async = defineFunction("baml.sys.pid", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;
