/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineInstanceFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";

/**
 * An array-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * An array-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  element_type = defineInstanceFunction("baml.reflect.array.Type.element_type", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
  element_type_async = defineInstanceFunction("baml.reflect.array.Type.element_type", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
}
