/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as ai from "../../ai/index.js";
import type * as baml from "../../baml/index.js";

export class Media$stream {
  media!: ai.MediaPart$stream | null;
  provider_id!: string | null;
  revised_prompt!: string | null;
  constructor(init: {
    media: ai.MediaPart$stream | null;
    provider_id: string | null;
    revised_prompt: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Reasoning$stream {
  summary!: string | null;
  constructor(init: {
    summary: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Text$stream {
  text!: string | null;
  constructor(init: {
    text: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolUse$stream {
  id!: string | null;
  name!: string | null;
  args!: { [key: string]: unknown };
  constructor(init: {
    id: string | null;
    name: string | null;
    args: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

export type Block$stream = Text$stream | Reasoning$stream | ToolUse$stream | Media$stream;

export class Text {
  text!: string;
  constructor(init: {
    text: string;
  }) {
    Object.assign(this, init);
  }
}

export class Reasoning {
  summary!: string;
  constructor(init: {
    summary: string;
  }) {
    Object.assign(this, init);
  }
}

export class ToolUse {
  id!: string;
  name!: string;
  args!: { [key: string]: unknown };
  constructor(init: {
    id: string;
    name: string;
    args: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

export class Media {
  media!: ai.MediaPart;
  provider_id!: string | null;
  revised_prompt!: string | null;
  constructor(init: {
    media: ai.MediaPart;
    provider_id: string | null;
    revised_prompt: string | null;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("ai.content.Media.new", "sync", ["value"], ["provider_id", "revised_prompt"]) as (value: baml.media.Image | baml.media.Audio | baml.media.Video | baml.media.Pdf, $opts?: { provider_id?: string | null | undefined; revised_prompt?: string | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Media;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("ai.content.Media.new", "async", ["value"], ["provider_id", "revised_prompt"]) as (value: baml.media.Image | baml.media.Audio | baml.media.Video | baml.media.Pdf, $opts?: { provider_id?: string | null | undefined; revised_prompt?: string | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Media>;
  kind = defineInstanceFunction("ai.content.Media.kind", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
  kind_async = defineInstanceFunction("ai.content.Media.kind", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
}

export type Block = Text | Reasoning | ToolUse | Media;

export enum StopReason {
  Complete = "Complete",
  ToolUse = "ToolUse",
  MaxTokens = "MaxTokens",
  Refused = "Refused",
}
