/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

/**
 * A WebSocket connection.
 */
export class WsStream$stream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A WebSocket connection.
 */
export class WsStream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Send a text frame.
 * @throws Io
 */
  send = defineInstanceFunction("baml.ws.WsStream.send", "sync", ["self", "text"]).bind(this) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Send a text frame.
 * @throws Io
 */
  send_async = defineInstanceFunction("baml.ws.WsStream.send", "async", ["self", "text"]).bind(this) as (text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * Receive the next text frame, or `null` after the connection closes.
 * @throws Io
 */
  next = defineInstanceFunction("baml.ws.WsStream.next", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;
/**
 * Receive the next text frame, or `null` after the connection closes.
 * @throws Io
 */
  next_async = defineInstanceFunction("baml.ws.WsStream.next", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;
/**
 * Close the connection.
 */
  close = defineInstanceFunction("baml.ws.WsStream.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * Close the connection.
 */
  close_async = defineInstanceFunction("baml.ws.WsStream.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}

/**
 * Open a WebSocket connection with additional request headers.
 * @throws Io
 * @throws Timeout
 */
export const connect = defineFunction("baml.ws.connect", "sync", ["url", "headers"], ["timeout"]) as (url: string, headers: { [key: string]: string }, $opts?: { timeout?: baml.time.Duration | undefined; $ctx?: BamlCallContext | undefined } | undefined) => WsStream;

/**
 * Open a WebSocket connection with additional request headers.
 * @throws Io
 * @throws Timeout
 */
export const connect_async = defineFunction("baml.ws.connect", "async", ["url", "headers"], ["timeout"]) as (url: string, headers: { [key: string]: string }, $opts?: { timeout?: baml.time.Duration | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<WsStream>;

/**
 * @throws Io
 * @throws Timeout
 */
export const _connect = defineFunction("baml.ws._connect", "sync", ["url", "headers", "timeout_nanos"]) as (url: string, headers: { [key: string]: string }, timeout_nanos: bigint, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => WsStream;

/**
 * @throws Io
 * @throws Timeout
 */
export const _connect_async = defineFunction("baml.ws._connect", "async", ["url", "headers", "timeout_nanos"]) as (url: string, headers: { [key: string]: string }, timeout_nanos: bigint, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<WsStream>;
