/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

/**
 * A primitive-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * A primitive-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}
