/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

export class Tool$stream {
  name!: string | null;
  description!: string | null;
  input_schema!: { [key: string]: unknown };
  handler!: unknown | null;
  raw_handler!: unknown | null;
  on_error!: ErrorMode | null;
  constructor(init: {
    name: string | null;
    description: string | null;
    input_schema: { [key: string]: unknown };
    handler: unknown | null;
    raw_handler: unknown | null;
    on_error: ErrorMode | null;
  }) {
    Object.assign(this, init);
  }
}

export class Toolbox$stream {
  entries!: Tool$stream[];
  constructor(init: {
    entries: Tool$stream[];
  }) {
    Object.assign(this, init);
  }
}

export enum ErrorMode {
  Report = "Report",
  Raise = "Raise",
}

export class Tool {
  name!: string;
  description!: string;
  input_schema!: { [key: string]: unknown };
  handler!: unknown | null;
  raw_handler!: ((arg0: { [key: string]: unknown }) => string) | null;
  on_error!: ErrorMode | null;
  constructor(init: {
    name: string;
    description: string;
    input_schema: { [key: string]: unknown };
    handler: unknown | null;
    raw_handler: ((arg0: { [key: string]: unknown }) => string) | null;
    on_error: ErrorMode | null;
  }) {
    Object.assign(this, init);
  }
  call = defineInstanceFunction("ai.tools.Tool.call", "sync", ["self", "args"]).bind(this) as (args: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
  call_async = defineInstanceFunction("ai.tools.Tool.call", "async", ["self", "args"]).bind(this) as (args: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
}

/**
 * @throws InvalidArgument
 * @throws Unsupported
 */
export const tool = defineFunction("ai.tools.tool", "sync", ["handler"], ["name", "description", "on_error"]) as (handler: unknown, $opts?: { name?: string | null | undefined; description?: string | null | undefined; on_error?: ErrorMode | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Tool;

/**
 * @throws InvalidArgument
 * @throws Unsupported
 */
export const tool_async = defineFunction("ai.tools.tool", "async", ["handler"], ["name", "description", "on_error"]) as (handler: unknown, $opts?: { name?: string | null | undefined; description?: string | null | undefined; on_error?: ErrorMode | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Tool>;

/**
 * @throws InvalidArgument
 */
export const raw_tool = defineFunction("ai.tools.raw_tool", "sync", ["name", "description", "input_schema", "handler"], ["on_error"]) as (name: string, description: string, input_schema: { [key: string]: unknown }, handler: (arg0: { [key: string]: unknown }) => string, $opts?: { on_error?: ErrorMode | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Tool;

/**
 * @throws InvalidArgument
 */
export const raw_tool_async = defineFunction("ai.tools.raw_tool", "async", ["name", "description", "input_schema", "handler"], ["on_error"]) as (name: string, description: string, input_schema: { [key: string]: unknown }, handler: (arg0: { [key: string]: unknown }) => string, $opts?: { on_error?: ErrorMode | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Tool>;

export class Toolbox {
  entries!: Tool[];
  constructor(init: {
    entries: Tool[];
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("ai.tools.Toolbox.new", "sync", ["tools"]) as (tools: Tool[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Toolbox;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("ai.tools.Toolbox.new", "async", ["tools"]) as (tools: Tool[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Toolbox>;
  list = defineInstanceFunction("ai.tools.Toolbox.list", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Tool[];
  list_async = defineInstanceFunction("ai.tools.Toolbox.list", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Tool[]>;
  get = defineInstanceFunction("ai.tools.Toolbox.get", "sync", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Tool | null;
  get_async = defineInstanceFunction("ai.tools.Toolbox.get", "async", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Tool | null>;
  is_empty = defineInstanceFunction("ai.tools.Toolbox.is_empty", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;
  is_empty_async = defineInstanceFunction("ai.tools.Toolbox.is_empty", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;
}
