/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as ai from "../../ai/index.js";
import type * as baml from "../../baml/index.js";

export class McpConnection$stream {
  server_name!: string | null;
  p!: baml.sys.Process$stream | null;
  next_id!: number | null;
  constructor(init: {
    server_name: string | null;
    p: baml.sys.Process$stream | null;
    next_id: number | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * @throws JsonSerializationError
 */
export const rpc_line = defineFunction("ai.mcp.rpc_line", "sync", ["id", "method", "params"]) as (id: number | null, method: string, params: { [key: string]: unknown } | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * @throws JsonSerializationError
 */
export const rpc_line_async = defineFunction("ai.mcp.rpc_line", "async", ["id", "method", "params"]) as (id: number | null, method: string, params: { [key: string]: unknown } | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

export class McpConnection {
  server_name!: string;
  p!: baml.sys.Process;
  next_id!: number;
  constructor(init: {
    server_name: string;
    p: baml.sys.Process;
    next_id: number;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws JsonSerializationError
 */
  static connect = defineFunction("ai.mcp.McpConnection.connect", "sync", ["name", "command", "args"], ["timeout_ms"]) as (name: string, command: string, args: string[], $opts?: { timeout_ms?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => McpConnection;
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws JsonSerializationError
 */
  static connect_async = defineFunction("ai.mcp.McpConnection.connect", "async", ["name", "command", "args"], ["timeout_ms"]) as (name: string, command: string, args: string[], $opts?: { timeout_ms?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<McpConnection>;
/**
 * @throws NetworkFailure
 */
  _send = defineInstanceFunction("ai.mcp.McpConnection._send", "sync", ["self", "line"]).bind(this) as (line: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * @throws NetworkFailure
 */
  _send_async = defineInstanceFunction("ai.mcp.McpConnection._send", "async", ["self", "line"]).bind(this) as (line: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws JsonSerializationError
 */
  _request = defineInstanceFunction("ai.mcp.McpConnection._request", "sync", ["self", "method", "params"]).bind(this) as (method: string, params: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws JsonSerializationError
 */
  _request_async = defineInstanceFunction("ai.mcp.McpConnection._request", "async", ["self", "method", "params"]).bind(this) as (method: string, params: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws JsonSerializationError
 */
  tools = defineInstanceFunction("ai.mcp.McpConnection.tools", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.tools.Tool[];
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws JsonSerializationError
 */
  tools_async = defineInstanceFunction("ai.mcp.McpConnection.tools", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.tools.Tool[]>;
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws JsonSerializationError
 */
  call_tool = defineInstanceFunction("ai.mcp.McpConnection.call_tool", "sync", ["self", "name", "args"]).bind(this) as (name: string, args: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
/**
 * @throws InvalidRequest
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws JsonSerializationError
 */
  call_tool_async = defineInstanceFunction("ai.mcp.McpConnection.call_tool", "async", ["self", "name", "args"]).bind(this) as (name: string, args: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
  close = defineInstanceFunction("ai.mcp.McpConnection.close", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
  close_async = defineInstanceFunction("ai.mcp.McpConnection.close", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
}
