/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";

/**
 * A literal-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

const __baml_new = defineFunction("baml.reflect.literal.new", "sync", ["value"]) as (value: string | number | boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
export { __baml_new as new };

export const new_async = defineFunction("baml.reflect.literal.new", "async", ["value"]) as (value: string | number | boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

/**
 * A literal-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}
