/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";

export const of_value = defineFunction("baml.type.of_value", "sync", ["v"]) as (v: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;

export const of_value_async = defineFunction("baml.type.of_value", "async", ["v"]) as (v: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
