/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type * as baml from "../../../baml/index.js";

/**
 * A reflection construction failed compiler-equivalent validation.
 */
export class CompilationError$stream {
  message!: string | null;
  diagnostics!: baml.reflect.Diagnostic$stream[];
  constructor(init: {
    message: string | null;
    diagnostics: baml.reflect.Diagnostic$stream[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Runtime evaluation failed after successful construction/compilation.
 */
export class EvaluationError$stream {
  message!: string | null;
  constructor(init: {
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A session rejected concurrent use.
 */
export class SessionBusy$stream {
  message!: string | null;
  constructor(init: {
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A reflection construction failed compiler-equivalent validation.
 */
export class CompilationError {
  message!: string;
  diagnostics!: baml.reflect.Diagnostic[];
  constructor(init: {
    message: string;
    diagnostics: baml.reflect.Diagnostic[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Runtime evaluation failed after successful construction/compilation.
 */
export class EvaluationError {
  message!: string;
  constructor(init: {
    message: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A session rejected concurrent use.
 */
export class SessionBusy {
  message!: string;
  constructor(init: {
    message: string;
  }) {
    Object.assign(this, init);
  }
}
