/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";

/**
 * The iterator implementation for an array.
 */
export class ArrayIterator$stream<T> {
  arr!: T[];
  idx!: number | null;
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    arr: T[];
    idx: number | null;
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
}

export class Chain$stream<T, E, E2> {
  first!: unknown | null;
  other!: unknown | null;
  first_done!: boolean | null;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    first: unknown | null;
    other: unknown | null;
    first_done: boolean | null;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E", "E2"] as const;
}

/**
 * A sentinel class returned by `baml.iter.Iterator.next` when there are no more elements to yield.
 */
export class Done$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export class Filter$stream<T, E, E2> {
  source!: unknown | null;
  predicate!: unknown;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    predicate: unknown;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E", "E2"] as const;
}

export class FilterMap$stream<T, R, E, E2> {
  source!: unknown | null;
  func!: unknown;
  $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    func: unknown;
    $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "R", "E", "E2"] as const;
}

export class FlatMap$stream<T, R, E, E2, E3> {
  source!: unknown | null;
  func!: unknown;
  inner!: unknown | Done$stream | null;
  $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    func: unknown;
    inner: unknown | Done$stream | null;
    $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "R", "E", "E2", "E3"] as const;
}

export class Flatten$stream<I, R, E, E3> {
  source!: unknown | null;
  inner!: unknown | Done$stream | null;
  $types?: { I?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    inner: unknown | Done$stream | null;
    $types?: { I?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["I", "R", "E", "E3"] as const;
}

export class Map$stream<T, R, E, E2> {
  source!: unknown | null;
  func!: unknown;
  $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    func: unknown;
    $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "R", "E", "E2"] as const;
}

export class Peekable$stream<T, E> {
  source!: unknown | null;
  buffer!: T | Done$stream | null;
  has_buffer!: boolean | null;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    buffer: T | Done$stream | null;
    has_buffer: boolean | null;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E"] as const;
}

export class Range$stream {
  i!: number | null;
  max!: number | null;
  step!: number | null;
  constructor(init: {
    i: number | null;
    max: number | null;
    step: number | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * An iterator that returns the same value a specified number of times.
 */
export class Repeat$stream<T> {
  value!: T | null;
  count!: number | null;
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    value: T | null;
    count: number | null;
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
}

export class StepBy$stream<T, E> {
  source!: unknown | null;
  n!: number | null;
  first!: boolean | null;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown | null;
    n: number | null;
    first: boolean | null;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E"] as const;
}

/**
 * A sentinel class returned by `baml.iter.Iterator.next` when there are no more elements to yield.
 */
export class Done {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export const flatten = defineFunction("baml.iter.flatten", "sync", ["src"], undefined, { typeParams: ["R", "E", "E3", "I"] }) as <R, E, E3, I>(src: unknown, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken; I?: BamlType | BamlTypeToken } | undefined } | undefined) => unknown;

export const flatten_async = defineFunction("baml.iter.flatten", "async", ["src"], undefined, { typeParams: ["R", "E", "E3", "I"] }) as <R, E, E3, I>(src: unknown, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken; I?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<unknown>;

/**
 * The iterator implementation for an array.
 */
export class ArrayIterator<T> {
  arr!: T[];
  idx!: number;
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    arr: T[];
    idx: number;
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
  static new = defineFunction("baml.iter.ArrayIterator.new", "sync", ["arr"]) as <T>(arr: T[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ArrayIterator<T>;
  static new_async = defineFunction("baml.iter.ArrayIterator.new", "async", ["arr"]) as <T>(arr: T[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ArrayIterator<T>>;
}

export class Range {
  i!: number;
  max!: number;
  step!: number;
  constructor(init: {
    i: number;
    max: number;
    step: number;
  }) {
    Object.assign(this, init);
  }
  static new = defineFunction("baml.iter.Range.new", "sync", ["min", "max"], ["step"]) as (min: number, max: number, $opts?: { step?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Range;
  static new_async = defineFunction("baml.iter.Range.new", "async", ["min", "max"], ["step"]) as (min: number, max: number, $opts?: { step?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Range>;
}

/**
 * An iterator that returns the same value a specified number of times.
 */
export class Repeat<T> {
  value!: T;
  count!: number;
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    value: T;
    count: number;
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
/**
 * Creates a new repeating iterator.
 * If `count` is negative (or not specified), it will repeat forever.
 */
  static new = defineFunction("baml.iter.Repeat.new", "sync", ["value"], ["count"]) as <T>(value: T, $opts?: { count?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Repeat<T>;
/**
 * Creates a new repeating iterator.
 * If `count` is negative (or not specified), it will repeat forever.
 */
  static new_async = defineFunction("baml.iter.Repeat.new", "async", ["value"], ["count"]) as <T>(value: T, $opts?: { count?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Repeat<T>>;
}

export class Map<T, R, E, E2> {
  source!: unknown;
  func!: (arg0: T) => R;
  $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    func: (arg0: T) => R;
    $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "R", "E", "E2"] as const;
}

export class Filter<T, E, E2> {
  source!: unknown;
  predicate!: (arg0: T) => boolean;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    predicate: (arg0: T) => boolean;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E", "E2"] as const;
}

export class FilterMap<T, R, E, E2> {
  source!: unknown;
  func!: (arg0: T) => R | null;
  $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    func: (arg0: T) => R | null;
    $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "R", "E", "E2"] as const;
}

export class FlatMap<T, R, E, E2, E3> {
  source!: unknown;
  func!: (arg0: T) => unknown;
  inner!: unknown | Done;
  $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    func: (arg0: T) => unknown;
    inner: unknown | Done;
    $types?: { T?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "R", "E", "E2", "E3"] as const;
}

export class Flatten<I, R, E, E3> {
  source!: unknown;
  inner!: unknown | Done;
  $types?: { I?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    inner: unknown | Done;
    $types?: { I?: BamlType | BamlTypeToken; R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E3?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["I", "R", "E", "E3"] as const;
}

export class Peekable<T, E> {
  source!: unknown;
  buffer!: T | Done;
  has_buffer!: boolean;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    buffer: T | Done;
    has_buffer: boolean;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E"] as const;
  peek = defineInstanceFunction("baml.iter.Peekable.peek", "sync", ["self"], undefined, { classTypeParams: ["T", "E"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => T | Done;
  peek_async = defineInstanceFunction("baml.iter.Peekable.peek", "async", ["self"], undefined, { classTypeParams: ["T", "E"] }).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<T | Done>;
}

export class StepBy<T, E> {
  source!: unknown;
  n!: number;
  first!: boolean;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  constructor(init: {
    source: unknown;
    n: number;
    first: boolean;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E"] as const;
}

export class Chain<T, E, E2> {
  first!: unknown;
  other!: unknown;
  first_done!: boolean;
  $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  constructor(init: {
    first: unknown;
    other: unknown;
    first_done: boolean;
    $types?: { T?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken; E2?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T", "E", "E2"] as const;
}

/** Erased runtime token for BAML interface `baml.iter.Iterable`. */
export const Iterable = Object.freeze({ __baml_interface_fqn__: "baml.iter.Iterable" } as const);

/** Erased runtime token for BAML interface `baml.iter.Iterator`. */
export const Iterator = Object.freeze({ __baml_interface_fqn__: "baml.iter.Iterator" } as const);
