/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

export type Item$stream = Table$stream | Item$stream[] | boolean | number | number | string | baml.time.ZonedDateTime$stream | baml.time.PlainDateTime$stream | baml.time.PlainDate$stream | baml.time.PlainTime$stream;

export type Item = Table | Item[] | boolean | number | number | string | baml.time.ZonedDateTime | baml.time.PlainDateTime | baml.time.PlainDate | baml.time.PlainTime;

/**
 * A TOML [table](https://toml.io/en/latest#table).
 * Represents a collection of key/value pairs.
 */
export class Table$stream {
  items!: { [key: string]: Item$stream };
  constructor(init: {
    items: { [key: string]: Item$stream };
  }) {
    Object.assign(this, init);
  }
}

export class TomlParseError$stream {
  message!: string | null;
  constructor(init: {
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A TOML [table](https://toml.io/en/latest#table).
 * Represents a collection of key/value pairs.
 */
export class Table {
  items!: { [key: string]: Item };
  constructor(init: {
    items: { [key: string]: Item };
  }) {
    Object.assign(this, init);
  }
/**
 * @throws TomlParseError
 */
  static parse = defineFunction("baml.toml.Table.parse", "sync", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Table;
/**
 * @throws TomlParseError
 */
  static parse_async = defineFunction("baml.toml.Table.parse", "async", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Table>;
}

/**
 * Decodes a JSON object into a `Table`, skipping null values. Returns a
 * concrete `Table` so arm-reachability over the recursive `json` map pattern
 * is analyzed without the abstract `Self` of `Table`'s `baml.FromJson` impl.
 * @throws JsonDecodeError
 */
export const table_from_json = defineFunction("baml.toml.table_from_json", "sync", ["j"]) as (j: baml.json.json, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Table;

/**
 * Decodes a JSON object into a `Table`, skipping null values. Returns a
 * concrete `Table` so arm-reachability over the recursive `json` map pattern
 * is analyzed without the abstract `Self` of `Table`'s `baml.FromJson` impl.
 * @throws JsonDecodeError
 */
export const table_from_json_async = defineFunction("baml.toml.table_from_json", "async", ["j"]) as (j: baml.json.json, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Table>;

/**
 * Converts a TOML item to a JSON value.
 * 
 * This is lossy: TOML datetime values are converted to JSON strings
 * (`ZonedDateTime` as RFC 3339, the `Plain*` types as zoneless ISO 8601).
 * @throws JsonSerializationError
 */
export const item_to_json = defineFunction("baml.toml.item_to_json", "sync", ["item"]) as (item: Item, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;

/**
 * Converts a TOML item to a JSON value.
 * 
 * This is lossy: TOML datetime values are converted to JSON strings
 * (`ZonedDateTime` as RFC 3339, the `Plain*` types as zoneless ISO 8601).
 * @throws JsonSerializationError
 */
export const item_to_json_async = defineFunction("baml.toml.item_to_json", "async", ["item"]) as (item: Item, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;

/**
 * Errors if the JSON value is `null`.
 * Usually `Table.from_json` is a better entrypoint, as it will skip null values without erroring.
 * @throws JsonDecodeError
 */
export const item_from_json = defineFunction("baml.toml.item_from_json", "sync", ["json"]) as (json: baml.json.json, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Item;

/**
 * Errors if the JSON value is `null`.
 * Usually `Table.from_json` is a better entrypoint, as it will skip null values without erroring.
 * @throws JsonDecodeError
 */
export const item_from_json_async = defineFunction("baml.toml.item_from_json", "async", ["json"]) as (json: baml.json.json, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Item>;

export class TomlParseError {
  message!: string;
  constructor(init: {
    message: string;
  }) {
    Object.assign(this, init);
  }
}
