/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";

/**
 * Internal sentinel returned when an incremental parse needs more text.
 */
export class NoYield$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * Cached type and assertion data used by incremental schema-aligned parsing.
 */
export class ParseCache$stream<TStream, TFinal> {
  _data!: _BamlHandle;
  $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken };
  constructor(init: {
    _data: _BamlHandle;
    $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["TStream", "TFinal"] as const;
}

/**
 * Cached type and assertion data used by incremental schema-aligned parsing.
 */
export class ParseCache<TStream, TFinal> {
  _data!: _BamlHandle;
  $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken };
  constructor(init: {
    _data: _BamlHandle;
    $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["TStream", "TFinal"] as const;
/**
 * Internal constructor. Callers normally use `__new_parse_cache` so the
 * type arguments determine both runtime type descriptors.
 */
  static new = defineFunction("baml.sap.ParseCache.new", "sync", ["t_stream", "t_final"]) as <TStream, TFinal>(t_stream: BamlType, t_final: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ParseCache<TStream, TFinal>;
/**
 * Internal constructor. Callers normally use `__new_parse_cache` so the
 * type arguments determine both runtime type descriptors.
 */
  static new_async = defineFunction("baml.sap.ParseCache.new", "async", ["t_stream", "t_final"]) as <TStream, TFinal>(t_stream: BamlType, t_final: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ParseCache<TStream, TFinal>>;
}

/**
 * Internal sentinel returned when an incremental parse needs more text.
 */
export class NoYield {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * Internal typed cache constructor shared by `ai.stream` and public SAP.
 */
export const __new_parse_cache = defineFunction("baml.sap.__new_parse_cache", "sync", [], undefined, { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>($opts?: { $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => ParseCache<TStream, TFinal>;

/**
 * Internal typed cache constructor shared by `ai.stream` and public SAP.
 */
export const __new_parse_cache_async = defineFunction("baml.sap.__new_parse_cache", "async", [], undefined, { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>($opts?: { $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<ParseCache<TStream, TFinal>>;

/**
 * Internal final SAP operation shared by streams and public SAP.
 * @throws LlmClient
 */
export const __parse_final = defineFunction("baml.sap.__parse_final", "sync", ["json", "cache"], undefined, { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>(json: string, cache: ParseCache<TStream, TFinal>, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => TFinal;

/**
 * Internal final SAP operation shared by streams and public SAP.
 * @throws LlmClient
 */
export const __parse_final_async = defineFunction("baml.sap.__parse_final", "async", ["json", "cache"], undefined, { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>(json: string, cache: ParseCache<TStream, TFinal>, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<TFinal>;

/**
 * Internal partial SAP operation used by `ai.stream.Stream`.
 * @throws LlmClient
 */
export const __parse_partial = defineFunction("baml.sap.__parse_partial", "sync", ["json", "cache"], undefined, { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>(json: string, cache: ParseCache<TStream, TFinal>, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => TStream | NoYield;

/**
 * Internal partial SAP operation used by `ai.stream.Stream`.
 * @throws LlmClient
 */
export const __parse_partial_async = defineFunction("baml.sap.__parse_partial", "async", ["json", "cache"], undefined, { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>(json: string, cache: ParseCache<TStream, TFinal>, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<TStream | NoYield>;

/**
 * Parse an LLM's raw text output into `T` with Schema-Aligned Parsing.
 * @throws LlmClient
 */
export const parse = defineFunction("baml.sap.parse", "sync", ["text"], undefined, { typeParams: ["T"] }) as <T>(text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * Parse an LLM's raw text output into `T` with Schema-Aligned Parsing.
 * @throws LlmClient
 */
export const parse_async = defineFunction("baml.sap.parse", "async", ["text"], undefined, { typeParams: ["T"] }) as <T>(text: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;

/**
 * Parse against a runtime `type` value when the schema is data rather than a
 * lexical type parameter. Narrow the returned `unknown` at the call site.
 * @throws LlmClient
 */
export const parse_type = defineFunction("baml.sap.parse_type", "sync", ["t", "text"]) as (t: BamlType, text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

/**
 * Parse against a runtime `type` value when the schema is data rather than a
 * lexical type parameter. Narrow the returned `unknown` at the call site.
 * @throws LlmClient
 */
export const parse_type_async = defineFunction("baml.sap.parse_type", "async", ["t", "text"]) as (t: BamlType, text: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;
