/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as vendor from "./vendor/index.js";

export { reflect } from "./baml/index.js";

export const main = defineFunction("user.main", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const main_async = defineFunction("user.main", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

export class AgentOutcome$stream {
  status!: "ready" | "needs-input" | "failed";
  summary!: string | null;
  artifact!: string | null;
  questions!: string[];
  checks_json!: string | null;
  constructor(init: {
    status: "ready" | "needs-input" | "failed";
    summary: string | null;
    artifact: string | null;
    questions: string[];
    checks_json: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class WorkflowAction$stream {
  kind!: "invoke" | "verify" | "review" | "await-input" | "await-approval" | "blocked" | "complete" | "cancelled";
  phase!: "requirements" | "plan" | "implementation" | "verification" | "review" | "handoff";
  prompt!: string | null;
  reason!: string | null;
  repair!: boolean | null;
  constructor(init: {
    kind: "invoke" | "verify" | "review" | "await-input" | "await-approval" | "blocked" | "complete" | "cancelled";
    phase: "requirements" | "plan" | "implementation" | "verification" | "review" | "handoff";
    prompt: string | null;
    reason: string | null;
    repair: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

export class WorkflowOutcome$stream {
  status!: "none" | "passed" | "failed" | "needs-input" | "error";
  summary!: string | null;
  constructor(init: {
    status: "none" | "passed" | "failed" | "needs-input" | "error";
    summary: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class WorkflowSnapshot$stream {
  phase!: "requirements" | "plan" | "implementation" | "verification" | "review" | "handoff";
  cancelled!: boolean | null;
  approval_valid!: boolean | null;
  repair_attempts!: number | null;
  policy_version!: string | null;
  capability_ready!: boolean | null;
  context!: string | null;
  constructor(init: {
    phase: "requirements" | "plan" | "implementation" | "verification" | "review" | "handoff";
    cancelled: boolean | null;
    approval_valid: boolean | null;
    repair_attempts: number | null;
    policy_version: string | null;
    capability_ready: boolean | null;
    context: string | null;
  }) {
    Object.assign(this, init);
  }
}

export type ActionKind$stream = "invoke" | "verify" | "review" | "await-input" | "await-approval" | "blocked" | "complete" | "cancelled";

export type OutcomeStatus$stream = "none" | "passed" | "failed" | "needs-input" | "error";

export type WorkflowPhase$stream = "requirements" | "plan" | "implementation" | "verification" | "review" | "handoff";

export type WorkflowPhase = "requirements" | "plan" | "implementation" | "verification" | "review" | "handoff";

export type OutcomeStatus = "none" | "passed" | "failed" | "needs-input" | "error";

export type ActionKind = "invoke" | "verify" | "review" | "await-input" | "await-approval" | "blocked" | "complete" | "cancelled";

export class WorkflowSnapshot {
  phase!: WorkflowPhase;
  cancelled!: boolean;
  approval_valid!: boolean;
  repair_attempts!: number;
  policy_version!: string;
  capability_ready!: boolean;
  context!: string;
  constructor(init: {
    phase: WorkflowPhase;
    cancelled: boolean;
    approval_valid: boolean;
    repair_attempts: number;
    policy_version: string;
    capability_ready: boolean;
    context: string;
  }) {
    Object.assign(this, init);
  }
}

export class WorkflowOutcome {
  status!: OutcomeStatus;
  summary!: string;
  constructor(init: {
    status: OutcomeStatus;
    summary: string;
  }) {
    Object.assign(this, init);
  }
}

export class WorkflowAction {
  kind!: ActionKind;
  phase!: WorkflowPhase;
  prompt!: string;
  reason!: string;
  repair!: boolean;
  constructor(init: {
    kind: ActionKind;
    phase: WorkflowPhase;
    prompt: string;
    reason: string;
    repair: boolean;
  }) {
    Object.assign(this, init);
  }
}

export class AgentOutcome {
  status!: "ready" | "needs-input" | "failed";
  summary!: string;
  artifact!: string;
  questions!: string[];
  checks_json!: string;
  constructor(init: {
    status: "ready" | "needs-input" | "failed";
    summary: string;
    artifact: string;
    questions: string[];
    checks_json: string;
  }) {
    Object.assign(this, init);
  }
}

export const policy_version = defineFunction("user.policy_version", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const policy_version_async = defineFunction("user.policy_version", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * @throws JsonDecodeError
 * @throws JsonParseError
 */
export const parse_agent_outcome = defineFunction("user.parse_agent_outcome", "sync", ["raw"]) as (raw: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => AgentOutcome;

/**
 * @throws JsonDecodeError
 * @throws JsonParseError
 */
export const parse_agent_outcome_async = defineFunction("user.parse_agent_outcome", "async", ["raw"]) as (raw: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<AgentOutcome>;

export const phase_prompt = defineFunction("user.phase_prompt", "sync", ["phase", "context"]) as (phase: WorkflowPhase, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const phase_prompt_async = defineFunction("user.phase_prompt", "async", ["phase", "context"]) as (phase: WorkflowPhase, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

export const action = defineFunction("user.action", "sync", ["kind", "phase", "reason", "context"], ["repair"]) as (kind: ActionKind, phase: WorkflowPhase, reason: string, context: string, $opts?: { repair?: boolean | undefined; $ctx?: BamlCallContext | undefined } | undefined) => WorkflowAction;

export const action_async = defineFunction("user.action", "async", ["kind", "phase", "reason", "context"], ["repair"]) as (kind: ActionKind, phase: WorkflowPhase, reason: string, context: string, $opts?: { repair?: boolean | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<WorkflowAction>;

export const next_step = defineFunction("user.next_step", "sync", ["snapshot", "outcome"]) as (snapshot: WorkflowSnapshot, outcome: WorkflowOutcome, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => WorkflowAction;

export const next_step_async = defineFunction("user.next_step", "async", ["snapshot", "outcome"]) as (snapshot: WorkflowSnapshot, outcome: WorkflowOutcome, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<WorkflowAction>;

export const fixture = defineFunction("user.fixture", "sync", ["phase"], ["approved", "repairs"]) as (phase: WorkflowPhase, $opts?: { approved?: boolean | undefined; repairs?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => WorkflowSnapshot;

export const fixture_async = defineFunction("user.fixture", "async", ["phase"], ["approved", "repairs"]) as (phase: WorkflowPhase, $opts?: { approved?: boolean | undefined; repairs?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<WorkflowSnapshot>;
