/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

/**
 * Thrown when YAML text cannot be parsed as a single JSON-compatible YAML
 * document.
 */
export class YamlParseError$stream {
  message!: string | null;
  constructor(init: {
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Thrown when YAML text cannot be parsed as a single JSON-compatible YAML
 * document.
 */
export class YamlParseError {
  message!: string;
  constructor(init: {
    message: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * @throws YamlParseError
 */
export const parse = defineFunction("baml.yaml.parse", "sync", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;

/**
 * @throws YamlParseError
 */
export const parse_async = defineFunction("baml.yaml.parse", "async", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;

/**
 * Parses YAML text and decodes it to `T`, honoring user-defined `baml.FromJson`
 * overrides (via `baml.json.from_json<T>`). The YAML counterpart of
 * `baml.json.deserialize<T>`. Parsing throws `YamlParseError`; decoding the
 * resulting `json` into `T` throws `JsonDecodeError` (decoding never re-parses,
 * so no `JsonParseError` arises here).
 * @throws YamlParseError
 * @throws JsonDecodeError
 */
export const deserialize = defineFunction("baml.yaml.deserialize", "sync", ["s"], undefined, { typeParams: ["T"] }) as <T>(s: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;

/**
 * Parses YAML text and decodes it to `T`, honoring user-defined `baml.FromJson`
 * overrides (via `baml.json.from_json<T>`). The YAML counterpart of
 * `baml.json.deserialize<T>`. Parsing throws `YamlParseError`; decoding the
 * resulting `json` into `T` throws `JsonDecodeError` (decoding never re-parses,
 * so no `JsonParseError` arises here).
 * @throws YamlParseError
 * @throws JsonDecodeError
 */
export const deserialize_async = defineFunction("baml.yaml.deserialize", "async", ["s"], undefined, { typeParams: ["T"] }) as <T>(s: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;
