/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

/**
 * A LATE-BOUND reference to an environment variable: pure data carrying the
 * variable's NAME, never its value.
 * 
 * `env.SOME_VAR` desugars to `baml.env.ref("SOME_VAR")`, which constructs one
 * of these. Nothing is read at construction time, so a `client Foo = ...`
 * declaration — evaluated during `$init`, which cannot run io sysops — can
 * name a variable without dying on an opaque `InitFailed`, and a host that
 * loads its secrets AFTER the runtime initializes still gets the fresh value:
 * the read happens at USE time, inside `get()`.
 * 
 * A `Ref` is also what keeps secrets out of constructed values. The name is
 * the only thing captured, so a client holding `api_key: env.OPENAI_API_KEY`
 * never has the key inside it — printing, serializing, or journaling that
 * client cannot leak the credential.
 *
 * Attributes:
 *   name: The environment variable's name. Never its value.
 */
export class Ref$stream {
  name!: string | null;
  constructor(init: {
    name: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Returns the value of the environment variable `key`, or `null` if not set.
 * 
 * Throws `ParseError` if the variable is set but its value is not valid
 * UTF-8 (the native bridge surfaces `std::env::VarError::NotUnicode` as a
 * catchable parse error).
 * @throws Io
 * @throws ParseError
 */
export const get = defineFunction("baml.env.get", "sync", ["key"]) as (key: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

/**
 * Returns the value of the environment variable `key`, or `null` if not set.
 * 
 * Throws `ParseError` if the variable is set but its value is not valid
 * UTF-8 (the native bridge surfaces `std::env::VarError::NotUnicode` as a
 * catchable parse error).
 * @throws Io
 * @throws ParseError
 */
export const get_async = defineFunction("baml.env.get", "async", ["key"]) as (key: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

/**
 * Returns the value of the environment variable `key`. Panics if not set.
 * @throws Io
 * @throws ParseError
 */
export const get_or_panic = defineFunction("baml.env.get_or_panic", "sync", ["key"]) as (key: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Returns the value of the environment variable `key`. Panics if not set.
 * @throws Io
 * @throws ParseError
 */
export const get_or_panic_async = defineFunction("baml.env.get_or_panic", "async", ["key"]) as (key: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * A LATE-BOUND reference to an environment variable: pure data carrying the
 * variable's NAME, never its value.
 * 
 * `env.SOME_VAR` desugars to `baml.env.ref("SOME_VAR")`, which constructs one
 * of these. Nothing is read at construction time, so a `client Foo = ...`
 * declaration — evaluated during `$init`, which cannot run io sysops — can
 * name a variable without dying on an opaque `InitFailed`, and a host that
 * loads its secrets AFTER the runtime initializes still gets the fresh value:
 * the read happens at USE time, inside `get()`.
 * 
 * A `Ref` is also what keeps secrets out of constructed values. The name is
 * the only thing captured, so a client holding `api_key: env.OPENAI_API_KEY`
 * never has the key inside it — printing, serializing, or journaling that
 * client cannot leak the credential.
 *
 * Attributes:
 *   name: The environment variable's name. Never its value.
 */
export class Ref {
  name!: string;
  constructor(init: {
    name: string;
  }) {
    Object.assign(this, init);
  }
/**
 * Read the variable now, or `null` when it is not set.
 * @throws Io
 * @throws ParseError
 */
  get = defineInstanceFunction("baml.env.Ref.get", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;
/**
 * Read the variable now, or `null` when it is not set.
 * @throws Io
 * @throws ParseError
 */
  get_async = defineInstanceFunction("baml.env.Ref.get", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;
/**
 * Read the variable now. Panics, naming the variable, when it is not set.
 * @throws Io
 * @throws ParseError
 */
  get_or_panic = defineInstanceFunction("baml.env.Ref.get_or_panic", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
/**
 * Read the variable now. Panics, naming the variable, when it is not set.
 * @throws Io
 * @throws ParseError
 */
  get_or_panic_async = defineInstanceFunction("baml.env.Ref.get_or_panic", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
/**
 * Read the variable now, falling back to `fallback` when it is not set.
 * @throws Io
 * @throws ParseError
 */
  or = defineInstanceFunction("baml.env.Ref.or", "sync", ["self", "fallback"]).bind(this) as (fallback: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;
/**
 * Read the variable now, falling back to `fallback` when it is not set.
 * @throws Io
 * @throws ParseError
 */
  or_async = defineInstanceFunction("baml.env.Ref.or", "async", ["self", "fallback"]).bind(this) as (fallback: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
}

/**
 * Construct a late-bound reference to the environment variable `name`.
 * 
 * This is what `env.NAME` sugar desugars to. It performs no io: the variable
 * is read when the returned `Ref` is used, not here.
 */
export const ref = defineFunction("baml.env.ref", "sync", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Ref;

/**
 * Construct a late-bound reference to the environment variable `name`.
 * 
 * This is what `env.NAME` sugar desugars to. It performs no io: the variable
 * is read when the returned `Ref` is used, not here.
 */
export const ref_async = defineFunction("baml.env.ref", "async", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Ref>;

/**
 * Like `get_or_panic`, but tolerant of a missing variable when `lenient` is
 * true: a missing variable yields the empty string instead of panicking.
 * 
 * Used by generated client constructors so that offline prompt rendering
 * (`<Fn>$render_prompt`) can build a client for its provider/role metadata
 * without requiring credentials. The network path (`<Fn>$call`) constructs
 * with `lenient = false`, so a missing `api_key` env var still panics for it,
 * exactly as before.
 * @throws Io
 * @throws ParseError
 */
export const get_or_panic_lenient = defineFunction("baml.env.get_or_panic_lenient", "sync", ["key", "lenient"]) as (key: string, lenient: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Like `get_or_panic`, but tolerant of a missing variable when `lenient` is
 * true: a missing variable yields the empty string instead of panicking.
 * 
 * Used by generated client constructors so that offline prompt rendering
 * (`<Fn>$render_prompt`) can build a client for its provider/role metadata
 * without requiring credentials. The network path (`<Fn>$call`) constructs
 * with `lenient = false`, so a missing `api_key` env var still panics for it,
 * exactly as before.
 * @throws Io
 * @throws ParseError
 */
export const get_or_panic_lenient_async = defineFunction("baml.env.get_or_panic_lenient", "async", ["key", "lenient"]) as (key: string, lenient: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;
