/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

export const equals_equals = defineFunction("baml.ops.equals_equals", "sync", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;

export const equals_equals_async = defineFunction("baml.ops.equals_equals", "async", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;

export const __union_add = defineFunction("baml.ops.__union_add", "sync", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const __union_add_async = defineFunction("baml.ops.__union_add", "async", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export const __union_sub = defineFunction("baml.ops.__union_sub", "sync", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const __union_sub_async = defineFunction("baml.ops.__union_sub", "async", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export const __union_mul = defineFunction("baml.ops.__union_mul", "sync", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const __union_mul_async = defineFunction("baml.ops.__union_mul", "async", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export const __union_div = defineFunction("baml.ops.__union_div", "sync", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const __union_div_async = defineFunction("baml.ops.__union_div", "async", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export const __union_rem = defineFunction("baml.ops.__union_rem", "sync", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const __union_rem_async = defineFunction("baml.ops.__union_rem", "async", ["a", "b"]) as (a: unknown, b: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export const __union_neg = defineFunction("baml.ops.__union_neg", "sync", ["a"]) as (a: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const __union_neg_async = defineFunction("baml.ops.__union_neg", "async", ["a"]) as (a: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;
