/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

/**
 * AES-128-GCM-SIV: nonce-misuse-resistant authenticated encryption (RFC 8452)
 * under a 128-bit key.
 * 
 * Identical in construction and guarantees to [`Aes256GcmSiv`], with a shorter
 * key. Prefer `Aes256GcmSiv` unless a 128-bit key is dictated by an existing
 * format or peer.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state: the expanded AES key schedule.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class Aes128GcmSiv$stream {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * AES-256-GCM-SIV: nonce-misuse-resistant authenticated encryption (RFC 8452)
 * under a 256-bit key.
 * 
 * The SIV construction derives each message's keystream counter, which is the
 * authentication tag itself, from the plaintext and `aad`. Repeating a
 * `(key, nonce)` pair therefore reveals only whether two messages were
 * identical. It does not leak the authentication key or the XOR of the two
 * plaintexts, both of which plain AES-GCM gives up on nonce reuse. That makes
 * AES-GCM-SIV the safer choice when nonces are drawn at random rather than
 * from a guaranteed-unique counter. It is not a reason to reuse a nonce, only
 * a limit on the damage when one repeats by accident.
 * 
 * ```
 * let rng = baml.random.SystemRandom.get();
 * let key = baml.crypto.Aes256GcmSiv.random_key(rng);
 * let cipher = baml.crypto.Aes256GcmSiv.new(key);
 * 
 * let nonce = rng.random(12);
 * let sealed = cipher.encrypt(nonce, plaintext, aad);
 * let opened = cipher.decrypt(nonce, sealed, aad);
 * ```
 * 
 * The nonce is not part of the ciphertext. Store or transmit it alongside.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state: the expanded AES key schedule.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class Aes256GcmSiv$stream {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * AES-256-GCM-SIV: nonce-misuse-resistant authenticated encryption (RFC 8452)
 * under a 256-bit key.
 * 
 * The SIV construction derives each message's keystream counter, which is the
 * authentication tag itself, from the plaintext and `aad`. Repeating a
 * `(key, nonce)` pair therefore reveals only whether two messages were
 * identical. It does not leak the authentication key or the XOR of the two
 * plaintexts, both of which plain AES-GCM gives up on nonce reuse. That makes
 * AES-GCM-SIV the safer choice when nonces are drawn at random rather than
 * from a guaranteed-unique counter. It is not a reason to reuse a nonce, only
 * a limit on the damage when one repeats by accident.
 * 
 * ```
 * let rng = baml.random.SystemRandom.get();
 * let key = baml.crypto.Aes256GcmSiv.random_key(rng);
 * let cipher = baml.crypto.Aes256GcmSiv.new(key);
 * 
 * let nonce = rng.random(12);
 * let sealed = cipher.encrypt(nonce, plaintext, aad);
 * let opened = cipher.decrypt(nonce, sealed, aad);
 * ```
 * 
 * The nonce is not part of the ciphertext. Store or transmit it alongside.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state: the expanded AES key schedule.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class Aes256GcmSiv {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("baml.crypto.Aes256GcmSiv.new", "sync", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Aes256GcmSiv;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("baml.crypto.Aes256GcmSiv.new", "async", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Aes256GcmSiv>;
}

/**
 * AES-128-GCM-SIV: nonce-misuse-resistant authenticated encryption (RFC 8452)
 * under a 128-bit key.
 * 
 * Identical in construction and guarantees to [`Aes256GcmSiv`], with a shorter
 * key. Prefer `Aes256GcmSiv` unless a 128-bit key is dictated by an existing
 * format or peer.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state: the expanded AES key schedule.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class Aes128GcmSiv {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("baml.crypto.Aes128GcmSiv.new", "sync", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Aes128GcmSiv;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("baml.crypto.Aes128GcmSiv.new", "async", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Aes128GcmSiv>;
}

/**
 * ChaCha20-Poly1305 (RFC 8439): authenticated encryption under a 256-bit key
 * with a 96-bit nonce.
 * 
 * A stream cipher paired with a one-time authenticator. It runs on ordinary
 * arithmetic rather than table lookups, so it is naturally constant-time and
 * fast in software. Prefer it over the AES ciphers on hardware without AES
 * instructions, and where a peer or format already specifies it (TLS, SSH,
 * WireGuard, `age`).
 * 
 * ```
 * let rng = baml.random.SystemRandom.get();
 * let key = baml.crypto.ChaCha20Poly1305.random_key(rng);
 * let cipher = baml.crypto.ChaCha20Poly1305.new(key);
 * 
 * let nonce = rng.random(12);
 * let sealed = cipher.encrypt(nonce, plaintext, aad);
 * let opened = cipher.decrypt(nonce, sealed, aad);
 * ```
 * 
 * ## Never reuse a nonce
 * 
 * Unlike [`Aes256GcmSiv`], this construction offers nothing when a
 * `(key, nonce)` pair repeats. Two messages encrypted under the same pair leak
 * the XOR of their plaintexts, and the repetition also exposes the Poly1305
 * key, which lets an attacker forge ciphertexts that authenticate. One repeat
 * is enough to lose both confidentiality and integrity for that key.
 * 
 * A 96-bit nonce is too small to draw at random for a long-lived key: at
 * random, repeats become likely after roughly 2^48 messages. Derive nonces from
 * a counter you know is unique, or use [`XChaCha20Poly1305`], whose 192-bit
 * nonce is large enough to draw at random.
 * 
 * The nonce is not part of the ciphertext. Store or transmit it alongside.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class ChaCha20Poly1305$stream {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * XChaCha20-Poly1305: [`ChaCha20Poly1305`] with a 192-bit nonce.
 * 
 * The extended nonce is the whole point. It is hashed down to a per-message
 * subkey before the standard construction runs, so the same 256-bit key,
 * stream cipher, and authenticator do the work, with a nonce large enough to
 * draw uniformly at random. At 192 bits, a repeat is negligible even across an
 * enormous number of messages, which removes the counter bookkeeping that
 * `ChaCha20Poly1305` demands.
 * 
 * Reach for this whenever nonces come from an RNG rather than from a counter
 * you control:
 * 
 * ```
 * let rng = baml.random.SystemRandom.get();
 * let key = baml.crypto.XChaCha20Poly1305.random_key(rng);
 * let cipher = baml.crypto.XChaCha20Poly1305.new(key);
 * 
 * let nonce = rng.random(24);
 * let sealed = cipher.encrypt(nonce, plaintext, aad);
 * let opened = cipher.decrypt(nonce, sealed, aad);
 * ```
 * 
 * A deliberately reused nonce still costs exactly what it costs for
 * `ChaCha20Poly1305`. The larger nonce makes an accidental collision
 * negligible; it does not make repetition safe.
 * 
 * The nonce is not part of the ciphertext. Store or transmit it alongside.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class XChaCha20Poly1305$stream {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * ChaCha20-Poly1305 (RFC 8439): authenticated encryption under a 256-bit key
 * with a 96-bit nonce.
 * 
 * A stream cipher paired with a one-time authenticator. It runs on ordinary
 * arithmetic rather than table lookups, so it is naturally constant-time and
 * fast in software. Prefer it over the AES ciphers on hardware without AES
 * instructions, and where a peer or format already specifies it (TLS, SSH,
 * WireGuard, `age`).
 * 
 * ```
 * let rng = baml.random.SystemRandom.get();
 * let key = baml.crypto.ChaCha20Poly1305.random_key(rng);
 * let cipher = baml.crypto.ChaCha20Poly1305.new(key);
 * 
 * let nonce = rng.random(12);
 * let sealed = cipher.encrypt(nonce, plaintext, aad);
 * let opened = cipher.decrypt(nonce, sealed, aad);
 * ```
 * 
 * ## Never reuse a nonce
 * 
 * Unlike [`Aes256GcmSiv`], this construction offers nothing when a
 * `(key, nonce)` pair repeats. Two messages encrypted under the same pair leak
 * the XOR of their plaintexts, and the repetition also exposes the Poly1305
 * key, which lets an attacker forge ciphertexts that authenticate. One repeat
 * is enough to lose both confidentiality and integrity for that key.
 * 
 * A 96-bit nonce is too small to draw at random for a long-lived key: at
 * random, repeats become likely after roughly 2^48 messages. Derive nonces from
 * a counter you know is unique, or use [`XChaCha20Poly1305`], whose 192-bit
 * nonce is large enough to draw at random.
 * 
 * The nonce is not part of the ciphertext. Store or transmit it alongside.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class ChaCha20Poly1305 {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("baml.crypto.ChaCha20Poly1305.new", "sync", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ChaCha20Poly1305;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("baml.crypto.ChaCha20Poly1305.new", "async", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ChaCha20Poly1305>;
}

/**
 * XChaCha20-Poly1305: [`ChaCha20Poly1305`] with a 192-bit nonce.
 * 
 * The extended nonce is the whole point. It is hashed down to a per-message
 * subkey before the standard construction runs, so the same 256-bit key,
 * stream cipher, and authenticator do the work, with a nonce large enough to
 * draw uniformly at random. At 192 bits, a repeat is negligible even across an
 * enormous number of messages, which removes the counter bookkeeping that
 * `ChaCha20Poly1305` demands.
 * 
 * Reach for this whenever nonces come from an RNG rather than from a counter
 * you control:
 * 
 * ```
 * let rng = baml.random.SystemRandom.get();
 * let key = baml.crypto.XChaCha20Poly1305.random_key(rng);
 * let cipher = baml.crypto.XChaCha20Poly1305.new(key);
 * 
 * let nonce = rng.random(24);
 * let sealed = cipher.encrypt(nonce, plaintext, aad);
 * let opened = cipher.decrypt(nonce, sealed, aad);
 * ```
 * 
 * A deliberately reused nonce still costs exactly what it costs for
 * `ChaCha20Poly1305`. The larger nonce makes an accidental collision
 * negligible; it does not make repetition safe.
 * 
 * The nonce is not part of the ciphertext. Store or transmit it alongside.
 *
 * Attributes:
 *   _cipher: Opaque, runtime-owned cipher state.
 *     
 *     The key lives here rather than in a `uint8array` field so that a cipher
 *     carrying a wrong-length key cannot be constructed, and so key material
 *     stays unreachable from BAML. It cannot be read back, rendered by
 *     `string.from`, or serialized by `baml.json.from`.
 */
export class XChaCha20Poly1305 {
  _cipher!: _BamlHandle;
  constructor(init: {
    _cipher: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("baml.crypto.XChaCha20Poly1305.new", "sync", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => XChaCha20Poly1305;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("baml.crypto.XChaCha20Poly1305.new", "async", ["key"]) as (key: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<XChaCha20Poly1305>;
}

/**
 * A ciphertext was rejected: it did not authenticate under the key, nonce, and
 * associated data it was decrypted with.
 * 
 * `reason` is coarse by design. AEAD authentication is all or nothing, and an
 * implementation that reported why a tag failed to verify would give an
 * attacker a decryption oracle. So `reason` never distinguishes a wrong key
 * from a wrong nonce, mismatched `aad`, or tampered ciphertext. It names only
 * facts the caller already holds, such as the ciphertext being too short to
 * contain a tag at all.
 *
 * Attributes:
 *   algorithm: The algorithm that rejected the ciphertext, such as `"AES-256-GCM-SIV"`.
 *   reason: A short description of the failure, never specific enough to identify
 *     which input was wrong.
 */
export class DecryptionFailure$stream {
  algorithm!: string | null;
  reason!: string | null;
  constructor(init: {
    algorithm: string | null;
    reason: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A ciphertext was rejected: it did not authenticate under the key, nonce, and
 * associated data it was decrypted with.
 * 
 * `reason` is coarse by design. AEAD authentication is all or nothing, and an
 * implementation that reported why a tag failed to verify would give an
 * attacker a decryption oracle. So `reason` never distinguishes a wrong key
 * from a wrong nonce, mismatched `aad`, or tampered ciphertext. It names only
 * facts the caller already holds, such as the ciphertext being too short to
 * contain a tag at all.
 *
 * Attributes:
 *   algorithm: The algorithm that rejected the ciphertext, such as `"AES-256-GCM-SIV"`.
 *   reason: A short description of the failure, never specific enough to identify
 *     which input was wrong.
 */
export class DecryptionFailure {
  algorithm!: string;
  reason!: string;
  constructor(init: {
    algorithm: string;
    reason: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * SHA-256, the 256-bit member of the SHA-2 family (FIPS 180-4).
 * 
 * Hashing is incremental. Feed the message in with `update`, in as many pieces
 * as convenient, then read the 32-byte digest with `finish`:
 * 
 * ```
 * let h = baml.crypto.Sha256.new();
 * h.update("hello".to_utf8());
 * h.update(" world".to_utf8());
 * h.finish().to_hex()  // b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
 * ```
 * 
 * A `Sha256` is a handle onto hasher state, not a value. Two references to the
 * same hasher feed the same digest, and `update` from separate `spawn` fibers
 * is serialized rather than racing. Use a fresh `Sha256.new()` per message.
 * 
 * SHA-256 is a plain hash, not a keyed one. It authenticates nothing on its
 * own: anyone can recompute the digest of a message they can guess. Do not use
 * it to check that a message came from who you think, and do not hash passwords
 * with it.
 *
 * Attributes:
 *   _state: Opaque, runtime-owned hasher state: the SHA-256 compression state and
 *     the buffered tail of the message so far.
 */
export class Sha256$stream {
  _state!: _BamlHandle;
  constructor(init: {
    _state: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * SHA-256, the 256-bit member of the SHA-2 family (FIPS 180-4).
 * 
 * Hashing is incremental. Feed the message in with `update`, in as many pieces
 * as convenient, then read the 32-byte digest with `finish`:
 * 
 * ```
 * let h = baml.crypto.Sha256.new();
 * h.update("hello".to_utf8());
 * h.update(" world".to_utf8());
 * h.finish().to_hex()  // b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9
 * ```
 * 
 * A `Sha256` is a handle onto hasher state, not a value. Two references to the
 * same hasher feed the same digest, and `update` from separate `spawn` fibers
 * is serialized rather than racing. Use a fresh `Sha256.new()` per message.
 * 
 * SHA-256 is a plain hash, not a keyed one. It authenticates nothing on its
 * own: anyone can recompute the digest of a message they can guess. Do not use
 * it to check that a message came from who you think, and do not hash passwords
 * with it.
 *
 * Attributes:
 *   _state: Opaque, runtime-owned hasher state: the SHA-256 compression state and
 *     the buffered tail of the message so far.
 */
export class Sha256 {
  _state!: _BamlHandle;
  constructor(init: {
    _state: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
  static new = defineFunction("baml.crypto.Sha256.new", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Sha256;
  static new_async = defineFunction("baml.crypto.Sha256.new", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Sha256>;
}
