/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";

/**
 * A union-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * @throws CompilationError
 */
const __baml_new = defineFunction("baml.reflect.union.new", "sync", ["types"]) as (types: BamlType[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
export { __baml_new as new };

/**
 * @throws CompilationError
 */
export const new_async = defineFunction("baml.reflect.union.new", "async", ["types"]) as (types: BamlType[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

/**
 * A union-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  member_types = defineInstanceFunction("baml.reflect.union.Type.member_types", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType[];
  member_types_async = defineInstanceFunction("baml.reflect.union.Type.member_types", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType[]>;
}
