/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";
import type * as ai from "../../ai/index.js";
import type * as baml from "../../baml/index.js";

/**
 * Mints a Google Cloud OAuth2 access token for `scope`, returning the bare
 * token (the caller builds the `Bearer` header).
 * 
 * `credentials_json` is an inline credential JSON document — service account,
 * authorized user, workload identity federation, or impersonated service
 * account: the same documents `GOOGLE_APPLICATION_CREDENTIALS` accepts. It is
 * used as-is: a broken document raises instead of silently falling back.
 * `null` runs the Application Default Credentials chain
 * (`GOOGLE_APPLICATION_CREDENTIALS`, the well-known ADC config file, the
 * gcloud config file, then the GCE metadata server).
 * 
 * Tokens are cached process-wide until shortly before expiry, so repeated
 * calls with the same credentials and scope do not re-mint.
 * @throws Io
 * @throws AccessError
 */
export const _gcp_access_token = defineFunction("ai.internal._gcp_access_token", "sync", ["credentials_json", "scope"]) as (credentials_json: string | null, scope: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Mints a Google Cloud OAuth2 access token for `scope`, returning the bare
 * token (the caller builds the `Bearer` header).
 * 
 * `credentials_json` is an inline credential JSON document — service account,
 * authorized user, workload identity federation, or impersonated service
 * account: the same documents `GOOGLE_APPLICATION_CREDENTIALS` accepts. It is
 * used as-is: a broken document raises instead of silently falling back.
 * `null` runs the Application Default Credentials chain
 * (`GOOGLE_APPLICATION_CREDENTIALS`, the well-known ADC config file, the
 * gcloud config file, then the GCE metadata server).
 * 
 * Tokens are cached process-wide until shortly before expiry, so repeated
 * calls with the same credentials and scope do not re-mint.
 * @throws Io
 * @throws AccessError
 */
export const _gcp_access_token_async = defineFunction("ai.internal._gcp_access_token", "async", ["credentials_json", "scope"]) as (credentials_json: string | null, scope: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * Resolves the Google Cloud project id from `credentials_json` when it carries
 * one, else from the google-auth chain (`GOOGLE_CLOUD_PROJECT` /
 * `GCLOUD_PROJECT`, the ADC and gcloud config files, the metadata server).
 * `null` means "not discoverable"; the caller decides whether that is fatal.
 * @throws Io
 * @throws AccessError
 */
export const _gcp_project_id = defineFunction("ai.internal._gcp_project_id", "sync", ["credentials_json"]) as (credentials_json: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

/**
 * Resolves the Google Cloud project id from `credentials_json` when it carries
 * one, else from the google-auth chain (`GOOGLE_CLOUD_PROJECT` /
 * `GCLOUD_PROJECT`, the ADC and gcloud config files, the metadata server).
 * `null` means "not discoverable"; the caller decides whether that is fatal.
 * @throws Io
 * @throws AccessError
 */
export const _gcp_project_id_async = defineFunction("ai.internal._gcp_project_id", "async", ["credentials_json"]) as (credentials_json: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

/**
 * Resolves the quota/billing project for the `x-goog-user-project` header,
 * matching google-auth's `Credentials.apply`: `GOOGLE_CLOUD_QUOTA_PROJECT`
 * always wins, then the credential document's `quota_project_id`.
 * @throws Io
 * @throws AccessError
 */
export const _gcp_quota_project_id = defineFunction("ai.internal._gcp_quota_project_id", "sync", ["credentials_json"]) as (credentials_json: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

/**
 * Resolves the quota/billing project for the `x-goog-user-project` header,
 * matching google-auth's `Credentials.apply`: `GOOGLE_CLOUD_QUOTA_PROJECT`
 * always wins, then the credential document's `quota_project_id`.
 * @throws Io
 * @throws AccessError
 */
export const _gcp_quota_project_id_async = defineFunction("ai.internal._gcp_quota_project_id", "async", ["credentials_json"]) as (credentials_json: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

/**
 * SigV4-signs `request` for `service` and returns it with the signature
 * headers applied (`authorization`, `x-amz-date`, and `x-amz-security-token`
 * for session credentials).
 * 
 * The signature covers the request's method, URL, headers, and body, so this
 * must be the LAST mutation of the request — anything added afterwards
 * invalidates it.
 * 
 * Credentials come from `access_key_id` + `secret_access_key` (+ optional
 * `session_token`) when both halves are present, else from the AWS provider
 * chain: environment, shared config/credentials files (static keys,
 * `credential_process`, SSO cache), the container endpoint, then EC2 IMDS.
 * @throws Io
 * @throws AccessError
 */
export const _aws_sign_request = defineFunction("ai.internal._aws_sign_request", "sync", ["request", "service", "region", "profile", "access_key_id", "secret_access_key", "session_token"]) as (request: baml.http.Request, service: string, region: string | null, profile: string | null, access_key_id: string | null, secret_access_key: string | null, session_token: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.http.Request;

/**
 * SigV4-signs `request` for `service` and returns it with the signature
 * headers applied (`authorization`, `x-amz-date`, and `x-amz-security-token`
 * for session credentials).
 * 
 * The signature covers the request's method, URL, headers, and body, so this
 * must be the LAST mutation of the request — anything added afterwards
 * invalidates it.
 * 
 * Credentials come from `access_key_id` + `secret_access_key` (+ optional
 * `session_token`) when both halves are present, else from the AWS provider
 * chain: environment, shared config/credentials files (static keys,
 * `credential_process`, SSO cache), the container endpoint, then EC2 IMDS.
 * @throws Io
 * @throws AccessError
 */
export const _aws_sign_request_async = defineFunction("ai.internal._aws_sign_request", "async", ["request", "service", "region", "profile", "access_key_id", "secret_access_key", "session_token"]) as (request: baml.http.Request, service: string, region: string | null, profile: string | null, access_key_id: string | null, secret_access_key: string | null, session_token: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.http.Request>;

/**
 * Resolves the AWS region: `region` when set, else `AWS_REGION`,
 * `AWS_DEFAULT_REGION`, or the active profile's `region` key. `null` means
 * "not discoverable".
 * @throws Io
 * @throws AccessError
 */
export const _aws_resolve_region = defineFunction("ai.internal._aws_resolve_region", "sync", ["region", "profile"]) as (region: string | null, profile: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

/**
 * Resolves the AWS region: `region` when set, else `AWS_REGION`,
 * `AWS_DEFAULT_REGION`, or the active profile's `region` key. `null` means
 * "not discoverable".
 * @throws Io
 * @throws AccessError
 */
export const _aws_resolve_region_async = defineFunction("ai.internal._aws_resolve_region", "async", ["region", "profile"]) as (region: string | null, profile: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

/**
 * The `"provider/model"` prefixes `ai.clients.resolve` understands, for error
 * messages.
 */
export const _shorthand_prefixes = defineFunction("ai.internal._shorthand_prefixes", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * The `"provider/model"` prefixes `ai.clients.resolve` understands, for error
 * messages.
 */
export const _shorthand_prefixes_async = defineFunction("ai.internal._shorthand_prefixes", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * @throws InvalidRequest
 */
export const _from_shorthand = defineFunction("ai.internal._from_shorthand", "sync", ["shorthand"]) as (shorthand: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

/**
 * @throws InvalidRequest
 */
export const _from_shorthand_async = defineFunction("ai.internal._from_shorthand", "async", ["shorthand"]) as (shorthand: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export class SpecCtx$stream {
  output_format!: string | null;
  constructor(init: {
    output_format: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * @throws Unsupported
 */
export const _schema_for_signature = defineFunction("ai.internal._schema_for_signature", "sync", ["handler"]) as (handler: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: unknown };

/**
 * @throws Unsupported
 */
export const _schema_for_signature_async = defineFunction("ai.internal._schema_for_signature", "async", ["handler"]) as (handler: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: unknown }>;

export class SpecCtx {
  output_format!: string;
  constructor(init: {
    output_format: string;
  }) {
    Object.assign(this, init);
  }
}

export const assemble_prompt = defineFunction("ai.internal.assemble_prompt", "sync", ["parts", "values"]) as (parts: string[], values: unknown[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.Prompt;

export const assemble_prompt_async = defineFunction("ai.internal.assemble_prompt", "async", ["parts", "values"]) as (parts: string[], values: unknown[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.Prompt>;

export const _header = defineFunction("ai.internal._header", "sync", ["headers", "lower", "canonical"]) as (headers: { [key: string]: string }, lower: string, canonical: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

export const _header_async = defineFunction("ai.internal._header", "async", ["headers", "lower", "canonical"]) as (headers: { [key: string]: string }, lower: string, canonical: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

export const _int_header = defineFunction("ai.internal._int_header", "sync", ["headers", "lower", "canonical"]) as (headers: { [key: string]: string }, lower: string, canonical: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number | null;

export const _int_header_async = defineFunction("ai.internal._int_header", "async", ["headers", "lower", "canonical"]) as (headers: { [key: string]: string }, lower: string, canonical: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number | null>;

export const _retry_after_ms = defineFunction("ai.internal._retry_after_ms", "sync", ["headers"]) as (headers: { [key: string]: string } | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number | null;

export const _retry_after_ms_async = defineFunction("ai.internal._retry_after_ms", "async", ["headers"]) as (headers: { [key: string]: string } | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number | null>;

export const _proxy = defineFunction("ai.internal._proxy", "sync", ["conn", "name"]) as (conn: ai.mcp.McpConnection, name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => (arg0: { [key: string]: unknown }) => string;

export const _proxy_async = defineFunction("ai.internal._proxy", "async", ["conn", "name"]) as (conn: ai.mcp.McpConnection, name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<(arg0: { [key: string]: unknown }) => string>;

export const _media_shape = defineFunction("ai.internal._media_shape", "sync", ["t"]) as (t: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const _media_shape_async = defineFunction("ai.internal._media_shape", "async", ["t"]) as (t: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * @throws UnknownError
 */
export const _media_envelope = defineFunction("ai.internal._media_envelope", "sync", ["m"]) as (m: ai.content.Media, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;

/**
 * @throws UnknownError
 */
export const _media_envelope_async = defineFunction("ai.internal._media_envelope", "async", ["m"]) as (m: ai.content.Media, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;

/**
 * @throws UnknownError
 */
export const _media_of_kind = defineFunction("ai.internal._media_of_kind", "sync", ["turn", "kind"]) as (turn: ai.ModelTurn, kind: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json[];

/**
 * @throws UnknownError
 */
export const _media_of_kind_async = defineFunction("ai.internal._media_of_kind", "async", ["turn", "kind"]) as (turn: ai.ModelTurn, kind: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json[]>;

/**
 * @throws UnknownError
 */
export const _media_mixed_parts = defineFunction("ai.internal._media_mixed_parts", "sync", ["turn"]) as (turn: ai.ModelTurn, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json[];

/**
 * @throws UnknownError
 */
export const _media_mixed_parts_async = defineFunction("ai.internal._media_mixed_parts", "async", ["turn"]) as (turn: ai.ModelTurn, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json[]>;

export const _media_all_text = defineFunction("ai.internal._media_all_text", "sync", ["items"]) as (items: baml.json.json[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;

export const _media_all_text_async = defineFunction("ai.internal._media_all_text", "async", ["items"]) as (items: baml.json.json[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;

export const _media_join_text = defineFunction("ai.internal._media_join_text", "sync", ["items"]) as (items: baml.json.json[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;

export const _media_join_text_async = defineFunction("ai.internal._media_join_text", "async", ["items"]) as (items: baml.json.json[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;

/**
 * @throws ParseFailed
 */
export const _media_reject_mixed = defineFunction("ai.internal._media_reject_mixed", "sync", ["turn", "kind", "provider"]) as (turn: ai.ModelTurn, kind: string, provider: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * @throws ParseFailed
 */
export const _media_reject_mixed_async = defineFunction("ai.internal._media_reject_mixed", "async", ["turn", "kind", "provider"]) as (turn: ai.ModelTurn, kind: string, provider: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

export const _media_mime_type = defineFunction("ai.internal._media_mime_type", "sync", ["explicit", "source_value", "kind"]) as (explicit: string | null, source_value: string, kind: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const _media_mime_type_async = defineFunction("ai.internal._media_mime_type", "async", ["explicit", "source_value", "kind"]) as (explicit: string | null, source_value: string, kind: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws Io
 */
export const _resolve_media_content = defineFunction("ai.internal._resolve_media_content", "sync", ["url", "file", "inline", "mime", "fetch_url"]) as (url: string | null, file: string | null, inline: string, mime: string, fetch_url: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.wire.ResolvedMedia;

/**
 * @throws NetworkFailure
 * @throws InvalidArgument
 * @throws Io
 */
export const _resolve_media_content_async = defineFunction("ai.internal._resolve_media_content", "async", ["url", "file", "inline", "mime", "fetch_url"]) as (url: string | null, file: string | null, inline: string, mime: string, fetch_url: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.wire.ResolvedMedia>;

export type OutputFormat$stream = ai.OutputFormat$stream;

/**
 * Reject output types that cannot be represented faithfully at the shared
 * LLM render boundary. Both prompt preview and execution call this guard.
 * @throws CompilationError
 */
export const validate_output_type = defineFunction("ai.internal.validate_output_type", "sync", ["return_type"]) as (return_type: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Reject output types that cannot be represented faithfully at the shared
 * LLM render boundary. Both prompt preview and execution call this guard.
 * @throws CompilationError
 */
export const validate_output_type_async = defineFunction("ai.internal.validate_output_type", "async", ["return_type"]) as (return_type: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

/**
 * Render a return type's schema with the default output-format options.
 */
export const render_output_format = defineFunction("ai.internal.render_output_format", "sync", ["return_type"]) as (return_type: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Render a return type's schema with the default output-format options.
 */
export const render_output_format_async = defineFunction("ai.internal.render_output_format", "async", ["return_type"]) as (return_type: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

export type OutputFormat = ai.OutputFormat;

/**
 * Build the output-format handle used by `root.Context.output_format_with`.
 */
export const build_output_format = defineFunction("ai.internal.build_output_format", "sync", ["return_type"]) as (return_type: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => OutputFormat;

/**
 * Build the output-format handle used by `root.Context.output_format_with`.
 */
export const build_output_format_async = defineFunction("ai.internal.build_output_format", "async", ["return_type"]) as (return_type: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<OutputFormat>;

/**
 * Construct a typed role marker for structural prompt assembly.
 * The `${role(...)}` desugar in an LLM prompt body lowers to this call.
 */
export const make_role = defineFunction("ai.internal.make_role", "sync", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.Role;

/**
 * Construct a typed role marker for structural prompt assembly.
 * The `${role(...)}` desugar in an LLM prompt body lowers to this call.
 */
export const make_role_async = defineFunction("ai.internal.make_role", "async", ["name"]) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.Role>;

/**
 * Look up an LLM function's declared return type. Retained for type-reflection
 * compatibility; the `ai.Agent` path uses lexical type arguments instead.
 * @throws InvalidArgument
 */
export const get_return_type = defineFunction("ai.internal.get_return_type", "sync", ["function_name"]) as (function_name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;

/**
 * Look up an LLM function's declared return type. Retained for type-reflection
 * compatibility; the `ai.Agent` path uses lexical type arguments instead.
 * @throws InvalidArgument
 */
export const get_return_type_async = defineFunction("ai.internal.get_return_type", "async", ["function_name"]) as (function_name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

export const _configured = defineFunction("ai.internal._configured", "sync", ["value"]) as (value: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | null;

export const _configured_async = defineFunction("ai.internal._configured", "async", ["value"]) as (value: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | null>;

export const _redact_after = defineFunction("ai.internal._redact_after", "sync", ["text", "marker"]) as (text: string, marker: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

export const _redact_after_async = defineFunction("ai.internal._redact_after", "async", ["text", "marker"]) as (text: string, marker: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

export const _redact_value_end = defineFunction("ai.internal._redact_value_end", "sync", ["tail"]) as (tail: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;

export const _redact_value_end_async = defineFunction("ai.internal._redact_value_end", "async", ["tail"]) as (tail: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;

export const _merge_json = defineFunction("ai.internal._merge_json", "sync", ["base", "patch"]) as (base: baml.json.json, patch: baml.json.json, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => baml.json.json;

export const _merge_json_async = defineFunction("ai.internal._merge_json", "async", ["base", "patch"]) as (base: baml.json.json, patch: baml.json.json, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<baml.json.json>;

export const _wire_blocks = defineFunction("ai.internal._wire_blocks", "sync", ["content", "keep_reasoning"]) as (content: ai.content.Block[], keep_reasoning: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.content.Block[];

export const _wire_blocks_async = defineFunction("ai.internal._wire_blocks", "async", ["content", "keep_reasoning"]) as (content: ai.content.Block[], keep_reasoning: boolean, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.content.Block[]>;

export const _flush_orphaned_calls = defineFunction("ai.internal._flush_orphaned_calls", "sync", ["out", "pending"]) as (out: ai.events.Event[], pending: string[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

export const _flush_orphaned_calls_async = defineFunction("ai.internal._flush_orphaned_calls", "async", ["out", "pending"]) as (out: ai.events.Event[], pending: string[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

export const _resolve_pending_call = defineFunction("ai.internal._resolve_pending_call", "sync", ["pending", "id"]) as (pending: string[], id: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

export const _resolve_pending_call_async = defineFunction("ai.internal._resolve_pending_call", "async", ["pending", "id"]) as (pending: string[], id: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
