/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";

/**
 * An immutable structural-conformance witness.  Values are created only by
 * `implementation<I>()`; each `field` call returns a new witness.
 */
export class Implementation$stream {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * An interface-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * An interface-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  implemented_by = defineInstanceFunction("baml.reflect.interface.Type.implemented_by", "sync", ["self", "other"]).bind(this) as (other: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;
  implemented_by_async = defineInstanceFunction("baml.reflect.interface.Type.implemented_by", "async", ["self", "other"]).bind(this) as (other: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;
}

/**
 * An immutable structural-conformance witness.  Values are created only by
 * `implementation<I>()`; each `field` call returns a new witness.
 */
export class Implementation {
  _handle!: _BamlHandle;
  constructor(init: {
    _handle: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws CompilationError
 */
  field = defineInstanceFunction("baml.reflect.interface.Implementation.field", "sync", ["self", "interface_field"], ["class_field"]).bind(this) as (interface_field: string, $opts?: { class_field?: string | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Implementation;
/**
 * @throws CompilationError
 */
  field_async = defineInstanceFunction("baml.reflect.interface.Implementation.field", "async", ["self", "interface_field"], ["class_field"]).bind(this) as (interface_field: string, $opts?: { class_field?: string | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Implementation>;
}

/**
 * @throws CompilationError
 */
export const implementation = defineFunction("baml.reflect.interface.implementation", "sync", [], undefined, { typeParams: ["I"] }) as <I>($opts?: { $ctx?: BamlCallContext | undefined; $types?: { I?: BamlType | BamlTypeToken } | undefined } | undefined) => Implementation;

/**
 * @throws CompilationError
 */
export const implementation_async = defineFunction("baml.reflect.interface.implementation", "async", [], undefined, { typeParams: ["I"] }) as <I>($opts?: { $ctx?: BamlCallContext | undefined; $types?: { I?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<Implementation>;
