/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type * as ai from "../../ai/index.js";

export class AssistantMessage$stream {
  content!: ai.content.Block$stream[];
  client_id!: string | null;
  constructor(init: {
    content: ai.content.Block$stream[];
    client_id: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class FinalProduced$stream {
  value_json!: string | null;
  constructor(init: {
    value_json: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class RunStarted$stream {
  spec_name!: string | null;
  arguments!: { [key: string]: unknown };
  constructor(init: {
    spec_name: string | null;
    arguments: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

export class ToolCompleted$stream {
  id!: string | null;
  output!: string | null;
  constructor(init: {
    id: string | null;
    output: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolFailed$stream {
  id!: string | null;
  message!: string | null;
  constructor(init: {
    id: string | null;
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolRequested$stream {
  id!: string | null;
  name!: string | null;
  args!: { [key: string]: unknown };
  constructor(init: {
    id: string | null;
    name: string | null;
    args: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

export class Usage$stream {
  input_tokens!: number | null;
  output_tokens!: number | null;
  cached_input_tokens!: number | null;
  reasoning_tokens!: number | null;
  constructor(init: {
    input_tokens: number | null;
    output_tokens: number | null;
    cached_input_tokens: number | null;
    reasoning_tokens: number | null;
  }) {
    Object.assign(this, init);
  }
}

export class UserMessage$stream {
  content!: string | null;
  constructor(init: {
    content: string | null;
  }) {
    Object.assign(this, init);
  }
}

export type Event$stream = RunStarted$stream | UserMessage$stream | AssistantMessage$stream | ToolRequested$stream | ToolCompleted$stream | ToolFailed$stream | Usage$stream | FinalProduced$stream;

export class RunStarted {
  spec_name!: string;
  arguments!: { [key: string]: unknown };
  constructor(init: {
    spec_name: string;
    arguments: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

export class UserMessage {
  content!: string;
  constructor(init: {
    content: string;
  }) {
    Object.assign(this, init);
  }
}

export class AssistantMessage {
  content!: ai.content.Block[];
  client_id!: string;
  constructor(init: {
    content: ai.content.Block[];
    client_id: string;
  }) {
    Object.assign(this, init);
  }
}

export class ToolRequested {
  id!: string;
  name!: string;
  args!: { [key: string]: unknown };
  constructor(init: {
    id: string;
    name: string;
    args: { [key: string]: unknown };
  }) {
    Object.assign(this, init);
  }
}

export class ToolCompleted {
  id!: string;
  output!: string;
  constructor(init: {
    id: string;
    output: string;
  }) {
    Object.assign(this, init);
  }
}

export class ToolFailed {
  id!: string;
  message!: string;
  constructor(init: {
    id: string;
    message: string;
  }) {
    Object.assign(this, init);
  }
}

export class Usage {
  input_tokens!: number;
  output_tokens!: number;
  cached_input_tokens!: number | null;
  reasoning_tokens!: number | null;
  constructor(init: {
    input_tokens: number;
    output_tokens: number;
    cached_input_tokens: number | null;
    reasoning_tokens: number | null;
  }) {
    Object.assign(this, init);
  }
}

export class FinalProduced {
  value_json!: string;
  constructor(init: {
    value_json: string;
  }) {
    Object.assign(this, init);
  }
}

export type Event = RunStarted | UserMessage | AssistantMessage | ToolRequested | ToolCompleted | ToolFailed | Usage | FinalProduced;
