/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, reflectType, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";
export * as array from "./array/index.js";
import * as __ns_class from "./class/index.js";
export { __ns_class as class };
import * as __ns_enum from "./enum/index.js";
export { __ns_enum as enum };
export * as errors from "./errors/index.js";
import * as __ns_function from "./function/index.js";
export { __ns_function as function };
import * as __ns_interface from "./interface/index.js";
export { __ns_interface as interface };
export * as literal from "./literal/index.js";
export * as map from "./map/index.js";
export * as primitive from "./primitive/index.js";
export * as union from "./union/index.js";
const __baml_type = reflectType;
export { __baml_type as type };

/**
 * One parameter of a function signature (BEP-062).
 *
 * Attributes:
 *   name: The parameter's name. When the callable carries no name for a
 *     positional parameter (a host callable from a language without
 *     parameter-name introspection), this is the placeholder `$argN` for
 *     position N. `$` cannot appear in a user identifier, so a placeholder
 *     can never collide with a declared parameter or named-argument key.
 *   type: The parameter's type.
 */
export class Arg$stream {
  name!: string | null;
  type!: unknown;
  constructor(init: {
    name: string | null;
    type: unknown;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The stable structured diagnostic surfaced by reflection constructors.
 */
export class Diagnostic$stream {
  code!: string | null;
  span!: Span$stream | null;
  message!: string | null;
  constructor(init: {
    code: string | null;
    span: Span$stream | null;
    message: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Thrown by `reflect.call_any` when the supplied arguments do not fit the
 * callee's runtime signature. `argument` names the offending key (`$argN`
 * placeholders included). An ill-typed value reports the parameter's and
 * the value's types; a missing required parameter reports the parameter's
 * type and `never`; a key naming no parameter reports the callee's whole
 * function type and the value's type.
 */
export class InvalidArgumentError$stream {
  argument!: string | null;
  expected!: unknown;
  got!: unknown;
  constructor(init: {
    argument: string | null;
    expected: unknown;
    got: unknown;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Metadata baked into reflected schema definitions.
 */
export class Meta$stream {
  alias!: string | null;
  description!: string | null;
  docstring!: string | null;
  other!: { [key: string]: string };
  constructor(init: {
    alias: string | null;
    description: string | null;
    docstring: string | null;
    other: { [key: string]: string };
  }) {
    Object.assign(this, init);
  }
}

/**
 * An isolated runtime-compiled package.
 */
export class Package$stream {
  _inner!: unknown;
  constructor(init: {
    _inner: unknown;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A live incremental evaluation environment. Its dependency aliases are
 * fixed at construction; every eval checks in a fresh compiler context and
 * commits successful statements to this Session's persistent runtime image.
 */
export class Session$stream {
  _inner!: unknown;
  constructor(init: {
    _inner: unknown;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The runtime signature of a function value, reconstructed from the value
 * itself (BEP-062). Positional (required) parameters appear in `args` in
 * declaration order; named/optional parameters appear in `opts`, keyed by
 * name. A bound method reports its receiver-adjusted signature (no `self`).
 *
 * Attributes:
 *   name: The name the function was declared with; null for host callables and
 *     compiler-synthesized callables (including lambdas).
 *   args: Positional (required) parameters, in order.
 *   opts: Named/optional parameters, keyed by parameter name.
 *   returns: The return type.
 *   errors: The error type; `never` if the function cannot throw.
 *   docstring: The function's doc comment (joined `///` lines); null when absent.
 */
export class Signature$stream {
  name!: string | null;
  args!: Arg$stream[];
  opts!: { [key: string]: Arg$stream };
  returns!: unknown;
  errors!: unknown;
  docstring!: string | null;
  constructor(init: {
    name: string | null;
    args: Arg$stream[];
    opts: { [key: string]: Arg$stream };
    returns: unknown;
    errors: unknown;
    docstring: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A source range attached to a compiler diagnostic. Compile- and eval-door
 * diagnostics carry their source range; structured construction diagnostics
 * report `span = null`, including constructors invoked from BAML.
 */
export class Span$stream {
  file!: string | null;
  start!: number | null;
  end!: number | null;
  constructor(init: {
    file: string | null;
    start: number | null;
    end: number | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A value paired with schema metadata. For type values this lets metadata be
 * attached without mutating the minted definition.
 */
export class WithMeta$stream<T> {
  ty!: T | null;
  alias!: string | null;
  description!: string | null;
  docstring!: string | null;
  other!: { [key: string]: string };
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    ty: T | null;
    alias: string | null;
    description: string | null;
    docstring: string | null;
    other: { [key: string]: string };
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
}

export type TypeKind$stream = baml.reflect.class.Type$stream | baml.reflect.enum.Type$stream | baml.reflect.union.Type$stream | baml.reflect.literal.Type$stream | baml.reflect.array.Type$stream | baml.reflect.map.Type$stream | baml.reflect.interface.Type$stream | baml.reflect.primitive.Type$stream | baml.reflect.function.Type$stream;

/**
 * One parameter of a function signature (BEP-062).
 *
 * Attributes:
 *   name: The parameter's name. When the callable carries no name for a
 *     positional parameter (a host callable from a language without
 *     parameter-name introspection), this is the placeholder `$argN` for
 *     position N. `$` cannot appear in a user identifier, so a placeholder
 *     can never collide with a declared parameter or named-argument key.
 *   type: The parameter's type.
 */
export class Arg {
  name!: string;
  type!: BamlType;
  constructor(init: {
    name: string;
    type: BamlType;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Metadata baked into reflected schema definitions.
 */
export class Meta {
  alias!: string | null;
  description!: string | null;
  docstring!: string | null;
  other!: { [key: string]: string };
  constructor(init: {
    alias: string | null;
    description: string | null;
    docstring: string | null;
    other: { [key: string]: string };
  }) {
    Object.assign(this, init);
  }
}

/**
 * A value paired with schema metadata. For type values this lets metadata be
 * attached without mutating the minted definition.
 */
export class WithMeta<T> {
  ty!: T;
  alias!: string | null;
  description!: string | null;
  docstring!: string | null;
  other!: { [key: string]: string };
  $types?: { T?: BamlType | BamlTypeToken };
  constructor(init: {
    ty: T;
    alias: string | null;
    description: string | null;
    docstring: string | null;
    other: { [key: string]: string };
    $types?: { T?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["T"] as const;
}

/**
 * A source range attached to a compiler diagnostic. Compile- and eval-door
 * diagnostics carry their source range; structured construction diagnostics
 * report `span = null`, including constructors invoked from BAML.
 */
export class Span {
  file!: string | null;
  start!: number;
  end!: number;
  constructor(init: {
    file: string | null;
    start: number;
    end: number;
  }) {
    Object.assign(this, init);
  }
}

/**
 * The stable structured diagnostic surfaced by reflection constructors.
 */
export class Diagnostic {
  code!: string;
  span!: Span | null;
  message!: string;
  constructor(init: {
    code: string;
    span: Span | null;
    message: string;
  }) {
    Object.assign(this, init);
  }
}

export type TypeKind = BamlType | BamlType | BamlType | BamlType | BamlType | BamlType | BamlType | BamlType | BamlType;

/**
 * The runtime signature of a function value, reconstructed from the value
 * itself (BEP-062). Positional (required) parameters appear in `args` in
 * declaration order; named/optional parameters appear in `opts`, keyed by
 * name. A bound method reports its receiver-adjusted signature (no `self`).
 *
 * Attributes:
 *   name: The name the function was declared with; null for host callables and
 *     compiler-synthesized callables (including lambdas).
 *   args: Positional (required) parameters, in order.
 *   opts: Named/optional parameters, keyed by parameter name.
 *   returns: The return type.
 *   errors: The error type; `never` if the function cannot throw.
 *   docstring: The function's doc comment (joined `///` lines); null when absent.
 */
export class Signature {
  name!: string | null;
  args!: Arg[];
  opts!: { [key: string]: Arg };
  returns!: BamlType;
  errors!: BamlType;
  docstring!: string | null;
  constructor(init: {
    name: string | null;
    args: Arg[];
    opts: { [key: string]: Arg };
    returns: BamlType;
    errors: BamlType;
    docstring: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Thrown by `reflect.call_any` when the supplied arguments do not fit the
 * callee's runtime signature. `argument` names the offending key (`$argN`
 * placeholders included). An ill-typed value reports the parameter's and
 * the value's types; a missing required parameter reports the parameter's
 * type and `never`; a key naming no parameter reports the callee's whole
 * function type and the value's type.
 */
export class InvalidArgumentError {
  argument!: string;
  expected!: BamlType;
  got!: BamlType;
  constructor(init: {
    argument: string;
    expected: BamlType;
    got: BamlType;
  }) {
    Object.assign(this, init);
  }
}

/**
 * An isolated runtime-compiled package.
 */
export class Package {
  _inner!: unknown;
  constructor(init: {
    _inner: unknown;
  }) {
    Object.assign(this, init);
  }
  static compile = defineFunction("baml.reflect.Package.compile", "sync", ["files"], ["packages"]) as (files: { [key: string]: string }, $opts?: { packages?: { [key: string]: Package } | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Package;
  static compile_async = defineFunction("baml.reflect.Package.compile", "async", ["files"], ["packages"]) as (files: { [key: string]: string }, $opts?: { packages?: { [key: string]: Package } | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Package>;
/**
 * @throws CompilationError
 */
  static _compile = defineFunction("baml.reflect.Package._compile", "sync", ["files", "packages"]) as (files: { [key: string]: string }, packages: { [key: string]: Package }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Package;
/**
 * @throws CompilationError
 */
  static _compile_async = defineFunction("baml.reflect.Package._compile", "async", ["files", "packages"]) as (files: { [key: string]: string }, packages: { [key: string]: Package }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Package>;
  static _finish = defineFunction("baml.reflect.Package._finish", "sync", ["artifact", "packages"]) as (artifact: Package, packages: { [key: string]: Package }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Package;
  static _finish_async = defineFunction("baml.reflect.Package._finish", "async", ["artifact", "packages"]) as (artifact: Package, packages: { [key: string]: Package }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Package>;
  get_class = defineInstanceFunction("baml.reflect.Package.get_class", "sync", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType | null;
  get_class_async = defineInstanceFunction("baml.reflect.Package.get_class", "async", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType | null>;
  get_enum = defineInstanceFunction("baml.reflect.Package.get_enum", "sync", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType | null;
  get_enum_async = defineInstanceFunction("baml.reflect.Package.get_enum", "async", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType | null>;
  get_interface = defineInstanceFunction("baml.reflect.Package.get_interface", "sync", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType | null;
  get_interface_async = defineInstanceFunction("baml.reflect.Package.get_interface", "async", ["self", "name"]).bind(this) as (name: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType | null>;
/**
 * @throws CompilationError
 */
  with_types = defineInstanceFunction("baml.reflect.Package.with_types", "sync", ["self", "types"]).bind(this) as (types: { [key: string]: BamlType | unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Package;
/**
 * @throws CompilationError
 */
  with_types_async = defineInstanceFunction("baml.reflect.Package.with_types", "async", ["self", "types"]).bind(this) as (types: { [key: string]: BamlType | unknown }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Package>;
/**
 * @throws CompilationError
 */
  get_function = defineInstanceFunction("baml.reflect.Package.get_function", "sync", ["self", "name"], undefined, { typeParams: ["F"] }).bind(this) as <F>(name: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { F?: BamlType | BamlTypeToken } | undefined } | undefined) => F | null;
/**
 * @throws CompilationError
 */
  get_function_async = defineInstanceFunction("baml.reflect.Package.get_function", "async", ["self", "name"], undefined, { typeParams: ["F"] }).bind(this) as <F>(name: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { F?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<F | null>;
  classes = defineInstanceFunction("baml.reflect.Package.classes", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: BamlType };
  classes_async = defineInstanceFunction("baml.reflect.Package.classes", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: BamlType }>;
  enums = defineInstanceFunction("baml.reflect.Package.enums", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: BamlType };
  enums_async = defineInstanceFunction("baml.reflect.Package.enums", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: BamlType }>;
  interfaces = defineInstanceFunction("baml.reflect.Package.interfaces", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: BamlType };
  interfaces_async = defineInstanceFunction("baml.reflect.Package.interfaces", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: BamlType }>;
  functions = defineInstanceFunction("baml.reflect.Package.functions", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: BamlType };
  functions_async = defineInstanceFunction("baml.reflect.Package.functions", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: BamlType }>;
  tests = defineInstanceFunction("baml.reflect.Package.tests", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => { [key: string]: () => null };
  tests_async = defineInstanceFunction("baml.reflect.Package.tests", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<{ [key: string]: () => null }>;
  diagnostics = defineInstanceFunction("baml.reflect.Package.diagnostics", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Diagnostic[];
  diagnostics_async = defineInstanceFunction("baml.reflect.Package.diagnostics", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Diagnostic[]>;
}

/**
 * A live incremental evaluation environment. Its dependency aliases are
 * fixed at construction; every eval checks in a fresh compiler context and
 * commits successful statements to this Session's persistent runtime image.
 */
export class Session {
  _inner!: unknown;
  constructor(init: {
    _inner: unknown;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws CompilationError
 */
  static new = defineFunction("baml.reflect.Session.new", "sync", [], ["packages"]) as ($opts?: { packages?: { [key: string]: Package } | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Session;
/**
 * @throws CompilationError
 */
  static new_async = defineFunction("baml.reflect.Session.new", "async", [], ["packages"]) as ($opts?: { packages?: { [key: string]: Package } | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Session>;
/**
 * @throws CompilationError
 */
  static _new = defineFunction("baml.reflect.Session._new", "sync", ["packages"]) as (packages: { [key: string]: Package }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Session;
/**
 * @throws CompilationError
 */
  static _new_async = defineFunction("baml.reflect.Session._new", "async", ["packages"]) as (packages: { [key: string]: Package }, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Session>;
/**
 * @throws CompilationError
 * @throws EvaluationError
 * @throws SessionBusy
 */
  eval = defineInstanceFunction("baml.reflect.Session.eval", "sync", ["self", "source"], undefined, { typeParams: ["T"] }).bind(this) as <T>(source: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;
/**
 * @throws CompilationError
 * @throws EvaluationError
 * @throws SessionBusy
 */
  eval_async = defineInstanceFunction("baml.reflect.Session.eval", "async", ["self", "source"], undefined, { typeParams: ["T"] }).bind(this) as <T>(source: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;
/**
 * @throws CompilationError
 * @throws SessionBusy
 */
  _compile = defineInstanceFunction("baml.reflect.Session._compile", "sync", ["self", "source"], undefined, { typeParams: ["T"] }).bind(this) as <T>(source: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Package;
/**
 * @throws CompilationError
 * @throws SessionBusy
 */
  _compile_async = defineInstanceFunction("baml.reflect.Session._compile", "async", ["self", "source"], undefined, { typeParams: ["T"] }).bind(this) as <T>(source: string, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<Package>;
  _finish = defineInstanceFunction("baml.reflect.Session._finish", "sync", ["self", "artifact"], undefined, { typeParams: ["T"] }).bind(this) as <T>(artifact: Package, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => T;
  _finish_async = defineInstanceFunction("baml.reflect.Session._finish", "async", ["self", "artifact"], undefined, { typeParams: ["T"] }).bind(this) as <T>(artifact: Package, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { T?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<T>;
  diagnostics = defineInstanceFunction("baml.reflect.Session.diagnostics", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Diagnostic[];
  diagnostics_async = defineInstanceFunction("baml.reflect.Session.diagnostics", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Diagnostic[]>;
}

export const signature = defineFunction("baml.reflect.signature", "sync", ["f"]) as (f: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Signature;

export const signature_async = defineFunction("baml.reflect.signature", "async", ["f"]) as (f: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Signature>;

/**
 * @throws InvalidArgumentError
 */
export const call_any = defineFunction("baml.reflect.call_any", "sync", ["f", "args"], undefined, { typeParams: ["R", "E"] }) as <R, E>(f: unknown, args: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken } | undefined } | undefined) => R;

/**
 * @throws InvalidArgumentError
 */
export const call_any_async = defineFunction("baml.reflect.call_any", "async", ["f", "args"], undefined, { typeParams: ["R", "E"] }) as <R, E>(f: unknown, args: { [key: string]: unknown }, $opts?: { $ctx?: BamlCallContext | undefined; $types?: { R?: BamlType | BamlTypeToken; E?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<R>;

/** Erased runtime token for BAML interface `baml.reflect.TypeView`. */
export const TypeView = Object.freeze({ __baml_interface_fqn__: "baml.reflect.TypeView" } as const);
