/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as ai from "../../ai/index.js";
import type * as baml from "../../baml/index.js";

export class Backoff$stream {
  initial_ms!: number | null;
  multiplier!: number | null;
  max_ms!: number | null;
  constructor(init: {
    initial_ms: number | null;
    multiplier: number | null;
    max_ms: number | null;
  }) {
    Object.assign(this, init);
  }
}

export class Fallback$stream {
  members!: unknown[];
  constructor(init: {
    members: unknown[];
  }) {
    Object.assign(this, init);
  }
}

export class Retry$stream {
  inner!: unknown | null;
  max_attempts!: number | null;
  retry_if!: unknown;
  backoff!: Backoff$stream | null;
  constructor(init: {
    inner: unknown | null;
    max_attempts: number | null;
    retry_if: unknown;
    backoff: Backoff$stream | null;
  }) {
    Object.assign(this, init);
  }
}

export class RoundRobin$stream {
  members!: unknown[];
  counter!: number | null;
  constructor(init: {
    members: unknown[];
    counter: number | null;
  }) {
    Object.assign(this, init);
  }
}

export type ClientSelector$stream = unknown | string | baml.env.Ref$stream;

export type ClientSelector = unknown | string | baml.env.Ref;

/**
 * Resolve a `ClientSelector` to the client to call, at CALL time.
 * 
 *   * a `root.Client` is returned unchanged (identity);
 *   * a string is the `"provider/model"` shorthand, constructed here — the
 *     runtime twin of the compiler's literal-`client:` lowering. An unknown
 *     prefix throws `root.errors.InvalidRequest` listing the valid ones;
 *   * a `baml.env.Ref` is read now and its value takes the string path. An
 *     UNSET variable is a typed `root.errors.InvalidRequest` naming it — not
 *     a panic, so a `catch_all` at the call boundary can still fall back.
 * 
 * This is what makes `client: env.MODEL.get() ?? "openai/gpt-4o-mini"` work:
 * nothing about the selection is decided until the call happens.
 * @throws InvalidRequest
 * @throws Io
 * @throws ParseError
 */
export const resolve = defineFunction("ai.clients.resolve", "sync", ["selector"]) as (selector: ClientSelector, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown;

/**
 * Resolve a `ClientSelector` to the client to call, at CALL time.
 * 
 *   * a `root.Client` is returned unchanged (identity);
 *   * a string is the `"provider/model"` shorthand, constructed here — the
 *     runtime twin of the compiler's literal-`client:` lowering. An unknown
 *     prefix throws `root.errors.InvalidRequest` listing the valid ones;
 *   * a `baml.env.Ref` is read now and its value takes the string path. An
 *     UNSET variable is a typed `root.errors.InvalidRequest` naming it — not
 *     a panic, so a `catch_all` at the call boundary can still fall back.
 * 
 * This is what makes `client: env.MODEL.get() ?? "openai/gpt-4o-mini"` work:
 * nothing about the selection is decided until the call happens.
 * @throws InvalidRequest
 * @throws Io
 * @throws ParseError
 */
export const resolve_async = defineFunction("ai.clients.resolve", "async", ["selector"]) as (selector: ClientSelector, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

export const default_retry_judgment = defineFunction("ai.clients.default_retry_judgment", "sync", ["f"]) as (f: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => boolean;

export const default_retry_judgment_async = defineFunction("ai.clients.default_retry_judgment", "async", ["f"]) as (f: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<boolean>;

export class Backoff {
  initial_ms!: number;
  multiplier!: number;
  max_ms!: number;
  constructor(init: {
    initial_ms: number;
    multiplier: number;
    max_ms: number;
  }) {
    Object.assign(this, init);
  }
  static new = defineFunction("ai.clients.Backoff.new", "sync", [], ["initial_ms", "multiplier", "max_ms"]) as ($opts?: { initial_ms?: number | undefined; multiplier?: number | undefined; max_ms?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Backoff;
  static new_async = defineFunction("ai.clients.Backoff.new", "async", [], ["initial_ms", "multiplier", "max_ms"]) as ($opts?: { initial_ms?: number | undefined; multiplier?: number | undefined; max_ms?: number | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Backoff>;
  delay_ms = defineInstanceFunction("ai.clients.Backoff.delay_ms", "sync", ["self", "attempt", "f"]).bind(this) as (attempt: number, f: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => number;
  delay_ms_async = defineInstanceFunction("ai.clients.Backoff.delay_ms", "async", ["self", "attempt", "f"]).bind(this) as (attempt: number, f: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<number>;
}

export class Retry {
  inner!: unknown;
  max_attempts!: number;
  retry_if!: (arg0: unknown) => boolean;
  backoff!: Backoff;
  constructor(init: {
    inner: unknown;
    max_attempts: number;
    retry_if: (arg0: unknown) => boolean;
    backoff: Backoff;
  }) {
    Object.assign(this, init);
  }
  static new = defineFunction("ai.clients.Retry.new", "sync", ["inner"], ["max_attempts", "retry_if", "backoff"]) as (inner: unknown, $opts?: { max_attempts?: number | undefined; retry_if?: ((arg0: unknown) => boolean) | null | undefined; backoff?: Backoff | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Retry;
  static new_async = defineFunction("ai.clients.Retry.new", "async", ["inner"], ["max_attempts", "retry_if", "backoff"]) as (inner: unknown, $opts?: { max_attempts?: number | undefined; retry_if?: ((arg0: unknown) => boolean) | null | undefined; backoff?: Backoff | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Retry>;
/**
 * @throws UnknownError
 */
  _attempt = defineInstanceFunction("ai.clients.Retry._attempt", "sync", ["self", "input", "remaining"]).bind(this) as (input: ai.ModelTurnInput, remaining: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.ModelTurn;
/**
 * @throws UnknownError
 */
  _attempt_async = defineInstanceFunction("ai.clients.Retry._attempt", "async", ["self", "input", "remaining"]).bind(this) as (input: ai.ModelTurnInput, remaining: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.ModelTurn>;
}

export class RoundRobin {
  members!: unknown[];
  counter!: number;
  constructor(init: {
    members: unknown[];
    counter: number;
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 */
  static new = defineFunction("ai.clients.RoundRobin.new", "sync", ["members"]) as (members: unknown[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => RoundRobin;
/**
 * @throws InvalidArgument
 */
  static new_async = defineFunction("ai.clients.RoundRobin.new", "async", ["members"]) as (members: unknown[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<RoundRobin>;
}

export class Fallback {
  members!: unknown[];
  constructor(init: {
    members: unknown[];
  }) {
    Object.assign(this, init);
  }
/**
 * @throws InvalidArgument
 * @throws UnknownError
 */
  _try = defineInstanceFunction("ai.clients.Fallback._try", "sync", ["self", "input", "index"]).bind(this) as (input: ai.ModelTurnInput, index: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.ModelTurn;
/**
 * @throws InvalidArgument
 * @throws UnknownError
 */
  _try_async = defineInstanceFunction("ai.clients.Fallback._try", "async", ["self", "input", "index"]).bind(this) as (input: ai.ModelTurnInput, index: number, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.ModelTurn>;
}
