/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType, type BamlTypeToken } from "@boundaryml/baml-bridge";
import type * as ai from "../../ai/index.js";
import type * as baml from "../../baml/index.js";

export class Done$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export class SseEvent$stream {
  event!: string | null;
  data!: string | null;
  id!: string | null;
  constructor(init: {
    event: string | null;
    data: string | null;
    id: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Stream$stream<TStream, TFinal> {
  _next_text!: unknown;
  _cache!: baml.sap.ParseCache$stream<TStream, TFinal> | null;
  _text!: string | null;
  _finished!: boolean | null;
  $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken };
  constructor(init: {
    _next_text: unknown;
    _cache: baml.sap.ParseCache$stream<TStream, TFinal> | null;
    _text: string | null;
    _finished: boolean | null;
    $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken };
  }) {
    Object.assign(this, init);
  }
  static readonly $generic = ["TStream", "TFinal"] as const;
}

export class TextDelta$stream {
  text!: string | null;
  constructor(init: {
    text: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class TurnDone$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export class TurnMeta$stream {
  stop_reason!: ai.content.StopReason | null;
  input_tokens!: number | null;
  output_tokens!: number | null;
  constructor(init: {
    stop_reason: ai.content.StopReason | null;
    input_tokens: number | null;
    output_tokens: number | null;
  }) {
    Object.assign(this, init);
  }
}

export class TurnStream$stream {
  _sse!: baml.http.SseStream$stream | null;
  _decode!: unknown | null;
  _chunks!: string[];
  _cursor!: number | null;
  _pending!: StreamEvent$stream[];
  _pcursor!: number | null;
  _text!: string | null;
  _stop_reason!: ai.content.StopReason | null;
  _input_tokens!: number | null;
  _output_tokens!: number | null;
  _done!: boolean | null;
  _require_terminal!: string | null;
  _saw_terminal!: boolean | null;
  constructor(init: {
    _sse: baml.http.SseStream$stream | null;
    _decode: unknown | null;
    _chunks: string[];
    _cursor: number | null;
    _pending: StreamEvent$stream[];
    _pcursor: number | null;
    _text: string | null;
    _stop_reason: ai.content.StopReason | null;
    _input_tokens: number | null;
    _output_tokens: number | null;
    _done: boolean | null;
    _require_terminal: string | null;
    _saw_terminal: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

export type StreamEvent$stream = TextDelta$stream | TurnMeta$stream | TurnDone$stream;

export class SseEvent {
  event!: string | null;
  data!: string | null;
  id!: string | null;
  constructor(init: {
    event: string | null;
    data: string | null;
    id: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * @throws JsonDecodeError
 * @throws JsonParseError
 */
export const decode_sse_batch = defineFunction("ai.stream.decode_sse_batch", "sync", ["batch"]) as (batch: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => SseEvent[];

/**
 * @throws JsonDecodeError
 * @throws JsonParseError
 */
export const decode_sse_batch_async = defineFunction("ai.stream.decode_sse_batch", "async", ["batch"]) as (batch: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<SseEvent[]>;

export class TextDelta {
  text!: string;
  constructor(init: {
    text: string;
  }) {
    Object.assign(this, init);
  }
}

export class TurnMeta {
  stop_reason!: ai.content.StopReason | null;
  input_tokens!: number | null;
  output_tokens!: number | null;
  constructor(init: {
    stop_reason: ai.content.StopReason | null;
    input_tokens: number | null;
    output_tokens: number | null;
  }) {
    Object.assign(this, init);
  }
}

export class TurnDone {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export type StreamEvent = TextDelta | TurnMeta | TurnDone;

export class Done {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

export class TurnStream {
  _sse!: baml.http.SseStream | null;
  _decode!: ((arg0: string) => StreamEvent[]) | null;
  _chunks!: string[];
  _cursor!: number;
  _pending!: StreamEvent[];
  _pcursor!: number;
  _text!: string;
  _stop_reason!: ai.content.StopReason | null;
  _input_tokens!: number | null;
  _output_tokens!: number | null;
  _done!: boolean;
  _require_terminal!: string | null;
  _saw_terminal!: boolean;
  constructor(init: {
    _sse: baml.http.SseStream | null;
    _decode: ((arg0: string) => StreamEvent[]) | null;
    _chunks: string[];
    _cursor: number;
    _pending: StreamEvent[];
    _pcursor: number;
    _text: string;
    _stop_reason: ai.content.StopReason | null;
    _input_tokens: number | null;
    _output_tokens: number | null;
    _done: boolean;
    _require_terminal: string | null;
    _saw_terminal: boolean;
  }) {
    Object.assign(this, init);
  }
  static from_sse = defineFunction("ai.stream.TurnStream.from_sse", "sync", ["sse", "decode"], ["require_terminal"]) as (sse: baml.http.SseStream, decode: (arg0: string) => StreamEvent[], $opts?: { require_terminal?: string | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => TurnStream;
  static from_sse_async = defineFunction("ai.stream.TurnStream.from_sse", "async", ["sse", "decode"], ["require_terminal"]) as (sse: baml.http.SseStream, decode: (arg0: string) => StreamEvent[], $opts?: { require_terminal?: string | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<TurnStream>;
  static from_chunks = defineFunction("ai.stream.TurnStream.from_chunks", "sync", ["chunks"]) as (chunks: string[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => TurnStream;
  static from_chunks_async = defineFunction("ai.stream.TurnStream.from_chunks", "async", ["chunks"]) as (chunks: string[], $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<TurnStream>;
  _finish = defineInstanceFunction("ai.stream.TurnStream._finish", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
  _finish_async = defineInstanceFunction("ai.stream.TurnStream._finish", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
/**
 * @throws NetworkFailure
 */
  _check_terminal = defineInstanceFunction("ai.stream.TurnStream._check_terminal", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;
/**
 * @throws NetworkFailure
 */
  _check_terminal_async = defineInstanceFunction("ai.stream.TurnStream._check_terminal", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
  next = defineInstanceFunction("ai.stream.TurnStream.next", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string | Done;
  next_async = defineInstanceFunction("ai.stream.TurnStream.next", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string | Done>;
  final_turn = defineInstanceFunction("ai.stream.TurnStream.final_turn", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.ModelTurn;
  final_turn_async = defineInstanceFunction("ai.stream.TurnStream.final_turn", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.ModelTurn>;
}

import { BamlStream as Stream } from "@boundaryml/baml-bridge";
export { Stream };

export const from_spec = defineFunction("ai.stream.from_spec", "sync", ["spec"], ["client"], { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>(spec: ai.FunctionSpec<TFinal>, $opts?: { client?: unknown | null | undefined; $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => Stream<TStream, TFinal>;

export const from_spec_async = defineFunction("ai.stream.from_spec", "async", ["spec"], ["client"], { typeParams: ["TStream", "TFinal"] }) as <TStream, TFinal>(spec: ai.FunctionSpec<TFinal>, $opts?: { client?: unknown | null | undefined; $ctx?: BamlCallContext | undefined; $types?: { TStream?: BamlType | BamlTypeToken; TFinal?: BamlType | BamlTypeToken } | undefined } | undefined) => Promise<Stream<TStream, TFinal>>;

/** Erased runtime token for BAML interface `ai.stream.StreamingClient`. */
export const StreamingClient = Object.freeze({ __baml_interface_fqn__: "ai.stream.StreamingClient" } as const);
