/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import type { BamlHandle as _BamlHandle } from "@boundaryml/baml-bridge";
import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

/**
 * A seedable, deterministic CSPRNG (ChaCha20). Given the same seed it always
 * reproduces the same stream. It is cryptographically secure *only* when seeded
 * with high-entropy input — e.g. 32 bytes drawn from `SystemRandom` (the
 * default when no seed is given). A low-entropy or attacker-known seed makes
 * its output predictable.
 *
 * Attributes:
 *   _state: Opaque, mutex-guarded generator state owned by the Rust runtime.
 */
export class ChaCha20$stream {
  _state!: _BamlHandle;
  constructor(init: {
    _state: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A cryptographically secure generator backed by the operating system's
 * entropy source (a CSPRNG). Draws fresh entropy on every call and is not
 * seedable, so it is non-deterministic and suitable for security-sensitive
 * randomness such as keys, tokens, and nonces.
 */
export class SystemRandom$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * A fast, seedable, deterministic PRNG (xoshiro256++). Given the same seed it
 * always reproduces the same stream, which makes it ideal for tests,
 * simulations, and sampling.
 * 
 * NOT cryptographically secure: its output is predictable from observed draws.
 * Never use it for keys, tokens, nonces, or any security-sensitive value — use
 * `SystemRandom` or a well-seeded `ChaCha20` instead.
 *
 * Attributes:
 *   _state: Opaque, mutex-guarded generator state owned by the Rust runtime.
 */
export class Xoshiro256PlusPlus$stream {
  _state!: _BamlHandle;
  constructor(init: {
    _state: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A cryptographically secure generator backed by the operating system's
 * entropy source (a CSPRNG). Draws fresh entropy on every call and is not
 * seedable, so it is non-deterministic and suitable for security-sensitive
 * randomness such as keys, tokens, and nonces.
 */
export class SystemRandom {
  constructor(init: {}) {
    Object.assign(this, init);
  }
/**
 * Returns a new `SystemRandom` instance using the global system random number generator.
 */
  static get = defineFunction("baml.random.SystemRandom.get", "sync", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => SystemRandom;
/**
 * Returns a new `SystemRandom` instance using the global system random number generator.
 */
  static get_async = defineFunction("baml.random.SystemRandom.get", "async", []) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<SystemRandom>;
}

/**
 * A fast, seedable, deterministic PRNG (xoshiro256++). Given the same seed it
 * always reproduces the same stream, which makes it ideal for tests,
 * simulations, and sampling.
 * 
 * NOT cryptographically secure: its output is predictable from observed draws.
 * Never use it for keys, tokens, nonces, or any security-sensitive value — use
 * `SystemRandom` or a well-seeded `ChaCha20` instead.
 *
 * Attributes:
 *   _state: Opaque, mutex-guarded generator state owned by the Rust runtime.
 */
export class Xoshiro256PlusPlus {
  _state!: _BamlHandle;
  constructor(init: {
    _state: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Creates a new `Xoshiro256PlusPlus` pseudo-random number generator.
 * 
 * ## Parameters
 * - `seed`: The seed for the random number generator.
 *   If no seed is provided, a random seed is generated using the system random number generator.
 *   The seed must be at least 32 bytes long.
 * 
 * ## Panics
 * If `seed` is shorter than 32 bytes.
 */
  static new = defineFunction("baml.random.Xoshiro256PlusPlus.new", "sync", [], ["seed"]) as ($opts?: { seed?: Uint8Array | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Xoshiro256PlusPlus;
/**
 * Creates a new `Xoshiro256PlusPlus` pseudo-random number generator.
 * 
 * ## Parameters
 * - `seed`: The seed for the random number generator.
 *   If no seed is provided, a random seed is generated using the system random number generator.
 *   The seed must be at least 32 bytes long.
 * 
 * ## Panics
 * If `seed` is shorter than 32 bytes.
 */
  static new_async = defineFunction("baml.random.Xoshiro256PlusPlus.new", "async", [], ["seed"]) as ($opts?: { seed?: Uint8Array | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<Xoshiro256PlusPlus>;
  static _new = defineFunction("baml.random.Xoshiro256PlusPlus._new", "sync", ["seed"]) as (seed: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Xoshiro256PlusPlus;
  static _new_async = defineFunction("baml.random.Xoshiro256PlusPlus._new", "async", ["seed"]) as (seed: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Xoshiro256PlusPlus>;
}

/**
 * A seedable, deterministic CSPRNG (ChaCha20). Given the same seed it always
 * reproduces the same stream. It is cryptographically secure *only* when seeded
 * with high-entropy input — e.g. 32 bytes drawn from `SystemRandom` (the
 * default when no seed is given). A low-entropy or attacker-known seed makes
 * its output predictable.
 *
 * Attributes:
 *   _state: Opaque, mutex-guarded generator state owned by the Rust runtime.
 */
export class ChaCha20 {
  _state!: _BamlHandle;
  constructor(init: {
    _state: _BamlHandle;
  }) {
    Object.assign(this, init);
  }
/**
 * Creates a new `ChaCha20` pseudo-random number generator.
 * 
 * ## Parameters
 * - `seed`: The seed for the random number generator.
 *   If no seed is provided, a random seed is generated using the system random number generator.
 *   The seed must be at least 32 bytes long.
 * 
 * ## Panics
 * If `seed` is shorter than 32 bytes.
 */
  static new = defineFunction("baml.random.ChaCha20.new", "sync", [], ["seed"]) as ($opts?: { seed?: Uint8Array | undefined; $ctx?: BamlCallContext | undefined } | undefined) => ChaCha20;
/**
 * Creates a new `ChaCha20` pseudo-random number generator.
 * 
 * ## Parameters
 * - `seed`: The seed for the random number generator.
 *   If no seed is provided, a random seed is generated using the system random number generator.
 *   The seed must be at least 32 bytes long.
 * 
 * ## Panics
 * If `seed` is shorter than 32 bytes.
 */
  static new_async = defineFunction("baml.random.ChaCha20.new", "async", [], ["seed"]) as ($opts?: { seed?: Uint8Array | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<ChaCha20>;
  static _new = defineFunction("baml.random.ChaCha20._new", "sync", ["seed"]) as (seed: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ChaCha20;
  static _new_async = defineFunction("baml.random.ChaCha20._new", "async", ["seed"]) as (seed: Uint8Array, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ChaCha20>;
}
