#!/usr/bin/env node
// Standalone, cleanup-only developer command for Latchkit-created generated
// output: build output, test/smoke fixtures, coverage, ad hoc debug logs,
// `npm pack` archives, local release staging, and orphaned temporary
// directories from an interrupted build/bundle/smoke run. It never rebuilds,
// installs dependencies, or launches a provider, and it never touches
// source files, `.latchkit/` project state, git history, worktrees, or
// branches -- it only ever considers the fixed, documented locations below.
//
// Usage:
//   node scripts/clean.js                 # dry run: report what would be removed
//   node scripts/clean.js --apply         # actually remove it
//   node scripts/clean.js --scope dist,coverage --apply
//   node scripts/clean.js --json          # machine-readable report
//
// `release-artifacts` (local release staging: archives, sidecars, retained
// `previous/` upgrade evidence, and qualification `.evidence.json` records)
// is intentionally excluded from the default scope. It is regenerable from
// source, but deciding which staged release is still referenced is release
// domain knowledge this command does not have; pass `--scope
// release-artifacts` to remove it explicitly and wholesale.
import { lstat, readdir, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(import.meta.dirname, '..');
const HOUR_MS = 60 * 60 * 1000;
export const DEFAULT_TMP_AGE_MS = 24 * HOUR_MS;
export const DEFAULT_SCOPES = Object.freeze([
  'dist',
  'test-results',
  'coverage',
  'typecheck-log',
  'tgz',
  'tmp',
]);
export const ALL_SCOPES = Object.freeze([...DEFAULT_SCOPES, 'release-artifacts']);

function fixedEntries(root) {
  return [
    {
      id: 'dist',
      scope: 'dist',
      kind: 'directory',
      path: path.join(root, 'dist'),
      retentionReason: 'Compiled application/browser output; fully regenerated by `npm run build`.',
    },
    {
      id: 'test-results',
      scope: 'test-results',
      kind: 'directory',
      path: path.join(root, 'test-results'),
      retentionReason:
        "Playwright's output directory, including the per-run acceptance/browser-crash " +
        'smoke fixtures created under it. Each run creates a uniquely named, self-contained ' +
        'fixture that nothing else references, so the whole directory is safe to reclaim ' +
        'between runs.',
    },
    {
      id: 'coverage',
      scope: 'coverage',
      kind: 'directory',
      path: path.join(root, 'coverage'),
      retentionReason:
        'Reserved output location for a coverage tool (not currently wired into any tracked ' +
        'command); included for forward compatibility with .gitignore.',
    },
    {
      id: 'typecheck-log',
      scope: 'typecheck-log',
      kind: 'file',
      path: path.join(root, '.latchkit-typecheck.log'),
      retentionReason:
        'Ad hoc developer-redirected `tsc` output; not produced by any tracked command.',
    },
  ];
}

async function globEntries(root, { suffix, scope, retentionReason }) {
  const entries = [];
  for (const name of await readdir(root).catch((error) => {
    if (error && error.code === 'ENOENT') return [];
    throw error;
  })) {
    if (name.endsWith(suffix))
      entries.push({
        id: `${scope}:${name}`,
        scope,
        kind: 'file',
        path: path.join(root, name),
        retentionReason,
      });
  }
  return entries;
}

async function releaseArtifactEntries(root) {
  const entries = [];
  for (const name of await readdir(root).catch((error) => {
    if (error && error.code === 'ENOENT') return [];
    throw error;
  })) {
    if (name !== 'release-artifacts' && !name.startsWith('release-artifacts-')) continue;
    entries.push({
      id: `release-artifacts:${name}`,
      scope: 'release-artifacts',
      kind: 'directory',
      path: path.join(root, name),
      retentionReason:
        'Local release staging (archives, sidecars, retained previous/ upgrade evidence, and ' +
        'qualification .evidence.json records). Regenerable from source via `npm run ' +
        'release:artifacts`, but not removed unless this scope is explicitly requested, since ' +
        'deciding which staged release is still referenced is release domain knowledge this ' +
        'command does not have.',
    });
  }
  return entries;
}

// The exact `mkdtemp` prefixes used by this repository's own build,
// bundling, packaging, and verification scripts (scripts/*.js only -- never
// the test suite's fixtures, which node:test already cleans up via t.after
// on every normal run). A machine can run other, unrelated processes that
// also create "latchkit-"-prefixed temporary directories (other sessions,
// manual exploration, agents working on other issues); matching only this
// exact allowlist -- not a broad "latchkit-*" wildcard -- keeps this scope
// from ever touching a directory this codebase did not itself create.
const SCRIPT_TMP_PREFIXES = Object.freeze([
  'latchkit-artifact-',
  'latchkit-bench-pack-source-',
  'latchkit-bench-pack-',
  'latchkit-bench-memory-',
  'latchkit-bench-diff-',
  'latchkit-native-smoke-',
  'latchkit-bundle-',
  'latchkit-live-lifecycle-outer-',
  'latchkit-live-lifecycle-',
  'latchkit-provider-adapter-',
  'latchkit-live-provider-',
  'latchkit-live-workflow-inner-',
  'latchkit-live-workflow-',
  'latchkit-release-verify-',
]);

async function tmpEntries(tmpRoot, now, olderThanMs) {
  const entries = [];
  for (const entry of await readdir(tmpRoot, { withFileTypes: true }).catch((error) => {
    if (error && error.code === 'ENOENT') return [];
    throw error;
  })) {
    if (
      !entry.isDirectory() ||
      !SCRIPT_TMP_PREFIXES.some((prefix) => entry.name.startsWith(prefix))
    )
      continue;
    const target = path.join(tmpRoot, entry.name);
    const info = await lstat(target).catch(() => null);
    if (!info || info.isSymbolicLink()) continue;
    const ageMs = now - info.mtimeMs;
    const eligible = ageMs >= olderThanMs;
    entries.push({
      id: `tmp:${entry.name}`,
      scope: 'tmp',
      kind: 'directory',
      path: target,
      eligible,
      retentionReason: eligible
        ? 'Orphaned scratch directory from an interrupted build/bundle/smoke run: its owning ' +
          '`finally` block never removed it, and it has outlived the retention window.'
        : `Scratch directory younger than the ${Math.round(olderThanMs / 60000)}-minute retention ` +
          'window; it may belong to a run still in progress and is left alone until it ages out.',
    });
  }
  return entries;
}

async function sizeOf(target) {
  const info = await lstat(target).catch(() => null);
  if (!info || info.isSymbolicLink()) return 0;
  if (info.isFile()) return info.size;
  if (!info.isDirectory()) return 0;
  let total = 0;
  for (const entry of await readdir(target, { withFileTypes: true })) {
    total += await sizeOf(path.join(target, entry.name));
  }
  return total;
}

async function classify(entry) {
  const info = await lstat(entry.path).catch(() => null);
  if (!info) return { ...entry, exists: false, bytes: 0, status: 'not-found' };
  if (info.isSymbolicLink())
    return {
      ...entry,
      exists: true,
      bytes: 0,
      status: 'retained',
      retainedReason: 'Refusing to remove a symbolic link or junction in place of the owned path.',
    };
  if (entry.kind === 'directory' && !info.isDirectory())
    return {
      ...entry,
      exists: true,
      bytes: 0,
      status: 'retained',
      retainedReason: `Expected a directory but found a ${info.isFile() ? 'file' : 'non-regular entry'}; not owned by this location's known shape.`,
    };
  if (entry.kind === 'file' && !info.isFile())
    return {
      ...entry,
      exists: true,
      bytes: 0,
      status: 'retained',
      retainedReason:
        "Expected a regular file but found a directory; not owned by this location's known shape.",
    };
  if (entry.eligible === false)
    return {
      ...entry,
      exists: true,
      bytes: await sizeOf(entry.path),
      status: 'retained',
      retainedReason: entry.retentionReason,
    };
  return { ...entry, exists: true, bytes: await sizeOf(entry.path), status: 'would-remove' };
}

// Computes what cleanup would do against live filesystem state. Never
// deletes anything -- safe to call for a preview, and called again inside
// applyCleanup immediately before each removal so apply always revalidates
// ownership and current use rather than trusting an earlier snapshot.
export async function planCleanup({
  root = repoRoot,
  tmpRoot = os.tmpdir(),
  now = Date.now(),
  olderThanMs = DEFAULT_TMP_AGE_MS,
  scopes = DEFAULT_SCOPES,
} = {}) {
  const requested = new Set(scopes);
  const unknown = [...requested].filter((scope) => !ALL_SCOPES.includes(scope));
  if (unknown.length) throw new Error(`Unknown cleanup scope: ${unknown.join(', ')}`);
  const candidates = fixedEntries(root).filter((entry) => requested.has(entry.scope));
  if (requested.has('tgz'))
    candidates.push(
      ...(await globEntries(root, {
        suffix: '.tgz',
        scope: 'tgz',
        retentionReason:
          '`npm pack` output; a development inspection artifact, not the release artifact.',
      })),
    );
  if (requested.has('release-artifacts')) candidates.push(...(await releaseArtifactEntries(root)));
  if (requested.has('tmp')) candidates.push(...(await tmpEntries(tmpRoot, now, olderThanMs)));
  const items = await Promise.all(candidates.map(classify));
  return {
    scopes: [...requested],
    items,
    totals: totalsOf(items, 'would-remove', 'bytesReclaimable', 'itemsToRemove'),
  };
}

function totalsOf(items, removableStatus, bytesKey, countKey) {
  return {
    [bytesKey]: items
      .filter((item) => item.status === removableStatus)
      .reduce((sum, item) => sum + item.bytes, 0),
    [countKey]: items.filter((item) => item.status === removableStatus).length,
    itemsRetained: items.filter((item) => item.status === 'retained').length,
  };
}

// Applies a plan from planCleanup. Every item is revalidated immediately
// before removal (existence, kind, link status, and -- for tmp entries --
// the retention-window check) so a plan computed earlier can never cause an
// apply pass to remove something that changed underneath it, and every
// resolved path is checked against the managed roots before deletion so a
// defect in a future entry definition can never escape them. Locked
// (typically Windows-only) files are retried with backoff; a removal that
// still fails is reported as retained with the reason rather than aborting
// the rest of the run.
export async function applyCleanup(plan, { root = repoRoot, tmpRoot = os.tmpdir() } = {}) {
  const boundaries = [path.resolve(root), path.resolve(tmpRoot)];
  const withinBoundary = (resolved) =>
    boundaries.some(
      (boundary) => resolved === boundary || resolved.startsWith(`${boundary}${path.sep}`),
    );
  const results = [];
  for (const item of plan.items) {
    if (item.status !== 'would-remove') {
      results.push(item);
      continue;
    }
    const resolved = path.resolve(item.path);
    if (!withinBoundary(resolved)) {
      results.push({
        ...item,
        status: 'retained',
        retainedReason: 'Resolved path escaped the managed cleanup roots; refusing to remove it.',
      });
      continue;
    }
    const revalidated = await classify(item);
    if (revalidated.status !== 'would-remove') {
      results.push(revalidated);
      continue;
    }
    try {
      await rm(resolved, { recursive: true, force: true, maxRetries: 8, retryDelay: 250 });
      results.push({ ...revalidated, status: 'removed' });
    } catch (error) {
      results.push({
        ...revalidated,
        status: 'retained',
        retainedReason: `Removal failed: ${error instanceof Error ? error.message : String(error)}`,
      });
    }
  }
  return {
    scopes: plan.scopes,
    items: results,
    totals: totalsOf(results, 'removed', 'bytesReclaimed', 'itemsRemoved'),
  };
}

function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  const units = ['KB', 'MB', 'GB'];
  let value = bytes / 1024;
  let unit = 0;
  while (value >= 1024 && unit < units.length - 1) {
    value /= 1024;
    unit += 1;
  }
  return `${value.toFixed(1)} ${units[unit]}`;
}

function report(mode, result) {
  console.log(`Latchkit cleanup (${mode}) -- scope: ${result.scopes.join(', ')}\n`);
  for (const item of result.items) {
    if (item.status === 'not-found') continue;
    const marker = { 'would-remove': '-', removed: 'x', retained: '!' }[item.status] ?? '?';
    console.log(
      `[${marker}] ${item.status.padEnd(12)} ${formatBytes(item.bytes).padStart(9)}  ${item.path}`,
    );
    if (item.status === 'retained')
      console.log(`      ${item.retainedReason ?? item.retentionReason}`);
  }
  console.log('');
  if (mode === 'apply')
    console.log(
      `Removed ${result.totals.itemsRemoved} item(s), reclaimed ${formatBytes(result.totals.bytesReclaimed)}. ${result.totals.itemsRetained} retained.`,
    );
  else
    console.log(
      `Would remove ${result.totals.itemsToRemove} item(s), reclaiming ${formatBytes(result.totals.bytesReclaimable)}. ${result.totals.itemsRetained} would be retained.\n` +
        'Dry run only -- pass --apply to remove these paths.',
    );
}

function valueAfter(args, name) {
  const index = args.indexOf(name);
  return index === -1 ? undefined : args[index + 1];
}

async function main() {
  const args = process.argv.slice(2);
  const apply = args.includes('--apply');
  const json = args.includes('--json');
  const scopeArgument = valueAfter(args, '--scope');
  const scopes = scopeArgument
    ? scopeArgument
        .split(',')
        .map((scope) => scope.trim())
        .filter(Boolean)
    : DEFAULT_SCOPES;
  const olderThanArgument = valueAfter(args, '--older-than-ms');
  const olderThanMs =
    olderThanArgument !== undefined ? Number(olderThanArgument) : DEFAULT_TMP_AGE_MS;
  // --root/--tmp-root exist mainly so this command can be exercised against
  // an isolated fixture in tests; the repository and the real OS temp root
  // are always the right defaults for actual developer use.
  const root = valueAfter(args, '--root') ?? repoRoot;
  const tmpRoot = valueAfter(args, '--tmp-root') ?? os.tmpdir();
  const plan = await planCleanup({ root, tmpRoot, scopes, olderThanMs });
  const result = apply ? await applyCleanup(plan, { root, tmpRoot }) : plan;
  if (json) console.log(JSON.stringify({ mode: apply ? 'apply' : 'dry-run', ...result }, null, 2));
  else report(apply ? 'apply' : 'dry-run', result);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url))
  main().catch((error) => {
    console.error(`Cleanup failed: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  });
