/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";
import type * as baml from "../../baml/index.js";

export class InvalidRequest$stream {
  provider!: string | null;
  status_code!: number | null;
  detail!: string | null;
  raw_body!: string | null;
  constructor(init: {
    provider: string | null;
    status_code: number | null;
    detail: string | null;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class NetworkFailure$stream {
  provider!: string | null;
  detail!: string | null;
  raw_body!: string | null;
  constructor(init: {
    provider: string | null;
    detail: string | null;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ParseFailed$stream {
  provider!: string | null;
  raw_output!: string | null;
  constructor(init: {
    provider: string | null;
    raw_output: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class RateLimited$stream {
  provider!: string | null;
  retry_after_ms!: number | null;
  raw_body!: string | null;
  constructor(init: {
    provider: string | null;
    retry_after_ms: number | null;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Refused$stream {
  provider!: string | null;
  reason!: string | null;
  raw_body!: string | null;
  constructor(init: {
    provider: string | null;
    reason: string | null;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class StepBudgetExceeded$stream {
  steps!: number | null;
  constructor(init: {
    steps: number | null;
  }) {
    Object.assign(this, init);
  }
}

export class StreamingUnsupported$stream {
  client_id!: string | null;
  constructor(init: {
    client_id: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ToolFailedError$stream {
  id!: string | null;
  name!: string | null;
  message!: string | null;
  cause!: unknown | null;
  constructor(init: {
    id: string | null;
    name: string | null;
    message: string | null;
    cause: unknown | null;
  }) {
    Object.assign(this, init);
  }
}

export enum RetrySafety {
  Safe = "Safe",
  Unknown = "Unknown",
  Unsafe = "Unsafe",
}

export const normalize = defineFunction("ai.errors.normalize", "sync", ["error"]) as (error: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => unknown | baml.errors.UnknownError;

export const normalize_async = defineFunction("ai.errors.normalize", "async", ["error"]) as (error: unknown, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown | baml.errors.UnknownError>;

export class RateLimited {
  provider!: string;
  retry_after_ms!: number | null;
  raw_body!: string | null;
  constructor(init: {
    provider: string;
    retry_after_ms: number | null;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class NetworkFailure {
  provider!: string;
  detail!: string;
  raw_body!: string | null;
  constructor(init: {
    provider: string;
    detail: string;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class InvalidRequest {
  provider!: string;
  status_code!: number | null;
  detail!: string;
  raw_body!: string | null;
  constructor(init: {
    provider: string;
    status_code: number | null;
    detail: string;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class Refused {
  provider!: string;
  reason!: string;
  raw_body!: string | null;
  constructor(init: {
    provider: string;
    reason: string;
    raw_body: string | null;
  }) {
    Object.assign(this, init);
  }
}

export class ParseFailed {
  provider!: string;
  raw_output!: string;
  constructor(init: {
    provider: string;
    raw_output: string;
  }) {
    Object.assign(this, init);
  }
}

export class StepBudgetExceeded {
  steps!: number;
  constructor(init: {
    steps: number;
  }) {
    Object.assign(this, init);
  }
}

export class ToolFailedError {
  id!: string;
  name!: string;
  message!: string;
  cause!: unknown | null;
  constructor(init: {
    id: string;
    name: string;
    message: string;
    cause: unknown | null;
  }) {
    Object.assign(this, init);
  }
}

export class StreamingUnsupported {
  client_id!: string;
  constructor(init: {
    client_id: string;
  }) {
    Object.assign(this, init);
  }
}

export const classify_http = defineFunction("ai.errors.classify_http", "sync", ["provider", "status_code", "body"], ["headers"]) as (provider: string, status_code: number, body: string, $opts?: { headers?: { [key: string]: string } | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => unknown;

export const classify_http_async = defineFunction("ai.errors.classify_http", "async", ["provider", "status_code", "body"], ["headers"]) as (provider: string, status_code: number, body: string, $opts?: { headers?: { [key: string]: string } | null | undefined; $ctx?: BamlCallContext | undefined } | undefined) => Promise<unknown>;

/** Erased runtime token for BAML interface `ai.errors.Failure`. */
export const Failure = Object.freeze({ __baml_interface_fqn__: "ai.errors.Failure" } as const);
