/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, type BamlCallContext } from "@boundaryml/baml-bridge";

/**
 * Reads a line of text from stdin. If `prompt` is provided, it is printed first (without a newline).
 */
export const input = defineFunction("baml.io.input", "sync", ["prompt"]) as (prompt: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => string;

/**
 * Reads a line of text from stdin. If `prompt` is provided, it is printed first (without a newline).
 */
export const input_async = defineFunction("baml.io.input", "async", ["prompt"]) as (prompt: string | null, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<string>;

/**
 * Write `s` to stdout with no trailing newline. Flushes immediately so the
 * bytes are visible before the next sysop or await suspends the thread.
 */
export const print = defineFunction("baml.io.print", "sync", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Write `s` to stdout with no trailing newline. Flushes immediately so the
 * bytes are visible before the next sysop or await suspends the thread.
 */
export const print_async = defineFunction("baml.io.print", "async", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

/**
 * Write `s` to stdout followed by a newline.
 */
export const println = defineFunction("baml.io.println", "sync", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Write `s` to stdout followed by a newline.
 */
export const println_async = defineFunction("baml.io.println", "async", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

/**
 * Like `print` but writes to stderr.
 */
export const eprint = defineFunction("baml.io.eprint", "sync", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Like `print` but writes to stderr.
 */
export const eprint_async = defineFunction("baml.io.eprint", "async", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;

/**
 * Like `println` but writes to stderr.
 */
export const eprintln = defineFunction("baml.io.eprintln", "sync", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => null;

/**
 * Like `println` but writes to stderr.
 */
export const eprintln_async = defineFunction("baml.io.eprintln", "async", ["s"]) as (s: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<null>;
