/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, defineInstanceFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";

/**
 * A map-kind view of a `type` value. Users never construct this class.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

const __baml_new = defineFunction("baml.reflect.map.new", "sync", ["key", "value"]) as (key: BamlType, value: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
export { __baml_new as new };

export const new_async = defineFunction("baml.reflect.map.new", "async", ["key", "value"]) as (key: BamlType, value: BamlType, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;

/**
 * A map-kind view of a `type` value. Users never construct this class.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  key_type = defineInstanceFunction("baml.reflect.map.Type.key_type", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
  key_type_async = defineInstanceFunction("baml.reflect.map.Type.key_type", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
  value_type = defineInstanceFunction("baml.reflect.map.Type.value_type", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
  value_type_async = defineInstanceFunction("baml.reflect.map.Type.value_type", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
}
