/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineInstanceFunction, type BamlCallContext, type BamlType } from "@boundaryml/baml-bridge";

export class Parameter {
  name!: string | null;
  type!: BamlType;
  optional!: boolean;
  constructor(init: {
    name: string | null;
    type: BamlType;
    optional: boolean;
  }) {
    Object.assign(this, init);
  }
}

export class Parameter$stream {
  name!: string | null;
  type!: unknown;
  optional!: boolean | null;
  constructor(init: {
    name: string | null;
    type: unknown;
    optional: boolean | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * A function-kind view of a `type` value. Throws are intentionally not part
 * of the function reflection surface.
 */
export class Type$stream {
  constructor(init: {}) {
    Object.assign(this, init);
  }
}

/**
 * A function-kind view of a `type` value. Throws are intentionally not part
 * of the function reflection surface.
 */
export class Type {
  constructor(init: {}) {
    Object.assign(this, init);
  }
  params = defineInstanceFunction("baml.reflect.function.Type.params", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Parameter[];
  params_async = defineInstanceFunction("baml.reflect.function.Type.params", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<Parameter[]>;
  return_type = defineInstanceFunction("baml.reflect.function.Type.return_type", "sync", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => BamlType;
  return_type_async = defineInstanceFunction("baml.reflect.function.Type.return_type", "async", ["self"]).bind(this) as ($opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<BamlType>;
}
